<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitolo 5 Analisi di dati genetici | Un viaggio nell’ambiente R</title>
  <meta name="description" content="Capitolo 5 Analisi di dati genetici | Un viaggio nell’ambiente R" />
  <meta name="generator" content="bookdown 0.21.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitolo 5 Analisi di dati genetici | Un viaggio nell’ambiente R" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitolo 5 Analisi di dati genetici | Un viaggio nell’ambiente R" />
  
  
  



<meta name="date" content="2021-04-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="base.html"/>
<link rel="next" href="machine-learning-in-r.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Copertina</a></li>
<li class="chapter" data-level="2" data-path="Prefazione.html"><a href="Prefazione.html"><i class="fa fa-check"></i><b>2</b> Prefazione</a></li>
<li class="chapter" data-level="3" data-path="Autori.html"><a href="Autori.html"><i class="fa fa-check"></i><b>3</b> Gli autori</a></li>
<li class="chapter" data-level="4" data-path="base.html"><a href="base.html"><i class="fa fa-check"></i><b>4</b> Le basi</a><ul>
<li class="chapter" data-level="4.1" data-path="base.html"><a href="base.html#R"><i class="fa fa-check"></i><b>4.1</b> Che cosa è l’ambiente R</a></li>
<li class="chapter" data-level="4.2" data-path="base.html"><a href="base.html#Russo"><i class="fa fa-check"></i><b>4.2</b> A cosa serve/non serve R</a></li>
<li class="chapter" data-level="4.3" data-path="base.html"><a href="base.html#WYSIWYM"><i class="fa fa-check"></i><b>4.3</b> “What You See Is What You Mean”: dallo Script al terminale (e viceversa)</a></li>
<li class="chapter" data-level="4.4" data-path="base.html"><a href="base.html#Espressioni"><i class="fa fa-check"></i><b>4.4</b> Le Espressioni</a></li>
<li class="chapter" data-level="4.5" data-path="base.html"><a href="base.html#Assegnazioni"><i class="fa fa-check"></i><b>4.5</b> Le Assegnazioni</a></li>
<li class="chapter" data-level="4.6" data-path="base.html"><a href="base.html#SintassiI"><i class="fa fa-check"></i><b>4.6</b> Sintassi di base (I): l’uso delle parentesi</a><ul>
<li class="chapter" data-level="4.6.1" data-path="base.html"><a href="base.html#le-parentesi-tonde"><i class="fa fa-check"></i><b>4.6.1</b> Le parentesi <strong>tonde</strong></a></li>
<li class="chapter" data-level="4.6.2" data-path="base.html"><a href="base.html#le-parentesi-quadre"><i class="fa fa-check"></i><b>4.6.2</b> Le parentesi <strong>quadre</strong></a></li>
<li class="chapter" data-level="4.6.3" data-path="base.html"><a href="base.html#le-parentesi-graffe"><i class="fa fa-check"></i><b>4.6.3</b> Le parentesi <strong>graffe</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="base.html"><a href="base.html#TipiDati"><i class="fa fa-check"></i><b>4.7</b> Tipologie di dati: gli attributi e le classi</a></li>
<li class="chapter" data-level="4.8" data-path="base.html"><a href="base.html#StruttureDati"><i class="fa fa-check"></i><b>4.8</b> Strutture di dati</a><ul>
<li class="chapter" data-level="4.8.1" data-path="base.html"><a href="base.html#vettori"><i class="fa fa-check"></i><b>4.8.1</b> Vettori</a></li>
<li class="chapter" data-level="4.8.2" data-path="base.html"><a href="base.html#matrici-e-array"><i class="fa fa-check"></i><b>4.8.2</b> Matrici (e Array)</a></li>
<li class="chapter" data-level="4.8.3" data-path="base.html"><a href="base.html#liste"><i class="fa fa-check"></i><b>4.8.3</b> Liste</a></li>
<li class="chapter" data-level="4.8.4" data-path="base.html"><a href="base.html#data-frame"><i class="fa fa-check"></i><b>4.8.4</b> Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="base.html"><a href="base.html#Funzioni"><i class="fa fa-check"></i><b>4.9</b> Sintassi di base (II): le funzioni</a></li>
<li class="chapter" data-level="4.10" data-path="base.html"><a href="base.html#Matrioske"><i class="fa fa-check"></i><b>4.10</b> Il mondo “a matrioske”</a></li>
<li class="chapter" data-level="4.11" data-path="base.html"><a href="base.html#Calcolo"><i class="fa fa-check"></i><b>4.11</b> La frontiera del calcolo: NA e NaN</a></li>
<li class="chapter" data-level="4.12" data-path="base.html"><a href="base.html#Boole"><i class="fa fa-check"></i><b>4.12</b> Operatori relazionali e algebra di Boole</a></li>
<li class="chapter" data-level="4.13" data-path="base.html"><a href="base.html#luso-dellhelp"><i class="fa fa-check"></i><b>4.13</b> L’uso dell’Help</a></li>
<li class="chapter" data-level="4.14" data-path="base.html"><a href="base.html#una-cassetta-degli-attrezzi-essenziali"><i class="fa fa-check"></i><b>4.14</b> Una cassetta degli attrezzi essenziali</a><ul>
<li class="chapter" data-level="4.14.1" data-path="base.html"><a href="base.html#c"><i class="fa fa-check"></i><b>4.14.1</b> c</a></li>
<li class="chapter" data-level="4.14.2" data-path="base.html"><a href="base.html#numeric"><i class="fa fa-check"></i><b>4.14.2</b> numeric</a></li>
<li class="chapter" data-level="4.14.3" data-path="base.html"><a href="base.html#character"><i class="fa fa-check"></i><b>4.14.3</b> character</a></li>
<li class="chapter" data-level="4.14.4" data-path="base.html"><a href="base.html#list"><i class="fa fa-check"></i><b>4.14.4</b> list</a></li>
<li class="chapter" data-level="4.14.5" data-path="base.html"><a href="base.html#matrix"><i class="fa fa-check"></i><b>4.14.5</b> matrix</a></li>
<li class="chapter" data-level="4.14.6" data-path="base.html"><a href="base.html#array"><i class="fa fa-check"></i><b>4.14.6</b> array</a></li>
<li class="chapter" data-level="4.14.7" data-path="base.html"><a href="base.html#data.frame"><i class="fa fa-check"></i><b>4.14.7</b> data.frame</a></li>
<li class="chapter" data-level="4.14.8" data-path="base.html"><a href="base.html#vector"><i class="fa fa-check"></i><b>4.14.8</b> vector</a></li>
<li class="chapter" data-level="4.14.9" data-path="base.html"><a href="base.html#rep"><i class="fa fa-check"></i><b>4.14.9</b> rep</a></li>
<li class="chapter" data-level="4.14.10" data-path="base.html"><a href="base.html#seq"><i class="fa fa-check"></i><b>4.14.10</b> seq</a></li>
<li class="chapter" data-level="4.14.11" data-path="base.html"><a href="base.html#head-e-tail"><i class="fa fa-check"></i><b>4.14.11</b> head e tail</a></li>
<li class="chapter" data-level="4.14.12" data-path="base.html"><a href="base.html#nrow-ncol-dim-e-length"><i class="fa fa-check"></i><b>4.14.12</b> nrow, ncol, dim e length</a></li>
<li class="chapter" data-level="4.14.13" data-path="base.html"><a href="base.html#str"><i class="fa fa-check"></i><b>4.14.13</b> str</a></li>
<li class="chapter" data-level="4.14.14" data-path="base.html"><a href="base.html#class"><i class="fa fa-check"></i><b>4.14.14</b> class</a></li>
<li class="chapter" data-level="4.14.15" data-path="base.html"><a href="base.html#unique"><i class="fa fa-check"></i><b>4.14.15</b> unique</a></li>
<li class="chapter" data-level="4.14.16" data-path="base.html"><a href="base.html#table"><i class="fa fa-check"></i><b>4.14.16</b> table</a></li>
<li class="chapter" data-level="4.14.17" data-path="base.html"><a href="base.html#rev-sort-e-order"><i class="fa fa-check"></i><b>4.14.17</b> rev, sort e order</a></li>
<li class="chapter" data-level="4.14.18" data-path="base.html"><a href="base.html#sample"><i class="fa fa-check"></i><b>4.14.18</b> sample</a></li>
<li class="chapter" data-level="4.14.19" data-path="base.html"><a href="base.html#apply"><i class="fa fa-check"></i><b>4.14.19</b> apply</a></li>
<li class="chapter" data-level="4.14.20" data-path="base.html"><a href="base.html#which"><i class="fa fa-check"></i><b>4.14.20</b> which</a></li>
<li class="chapter" data-level="4.14.21" data-path="base.html"><a href="base.html#match"><i class="fa fa-check"></i><b>4.14.21</b> match</a></li>
<li class="chapter" data-level="4.14.22" data-path="base.html"><a href="base.html#intersect"><i class="fa fa-check"></i><b>4.14.22</b> intersect</a></li>
<li class="chapter" data-level="4.14.23" data-path="base.html"><a href="base.html#setdiff"><i class="fa fa-check"></i><b>4.14.23</b> setdiff</a></li>
<li class="chapter" data-level="4.14.24" data-path="base.html"><a href="base.html#union"><i class="fa fa-check"></i><b>4.14.24</b> union</a></li>
<li class="chapter" data-level="4.14.25" data-path="base.html"><a href="base.html#merge"><i class="fa fa-check"></i><b>4.14.25</b> merge</a></li>
<li class="chapter" data-level="4.14.26" data-path="base.html"><a href="base.html#cbind"><i class="fa fa-check"></i><b>4.14.26</b> cbind</a></li>
<li class="chapter" data-level="4.14.27" data-path="base.html"><a href="base.html#rbind"><i class="fa fa-check"></i><b>4.14.27</b> rbind</a></li>
<li class="chapter" data-level="4.14.28" data-path="base.html"><a href="base.html#min-max-range"><i class="fa fa-check"></i><b>4.14.28</b> min, max, range</a></li>
<li class="chapter" data-level="4.14.29" data-path="base.html"><a href="base.html#summary"><i class="fa fa-check"></i><b>4.14.29</b> summary</a></li>
<li class="chapter" data-level="4.14.30" data-path="base.html"><a href="base.html#cumsum"><i class="fa fa-check"></i><b>4.14.30</b> cumsum</a></li>
<li class="chapter" data-level="4.14.31" data-path="base.html"><a href="base.html#median"><i class="fa fa-check"></i><b>4.14.31</b> median</a></li>
<li class="chapter" data-level="4.14.32" data-path="base.html"><a href="base.html#quantile"><i class="fa fa-check"></i><b>4.14.32</b> quantile</a></li>
<li class="chapter" data-level="4.14.33" data-path="base.html"><a href="base.html#mean"><i class="fa fa-check"></i><b>4.14.33</b> mean</a></li>
<li class="chapter" data-level="4.14.34" data-path="base.html"><a href="base.html#sd"><i class="fa fa-check"></i><b>4.14.34</b> sd</a></li>
<li class="chapter" data-level="4.14.35" data-path="base.html"><a href="base.html#runif"><i class="fa fa-check"></i><b>4.14.35</b> runif</a></li>
<li class="chapter" data-level="4.14.36" data-path="base.html"><a href="base.html#rnorm"><i class="fa fa-check"></i><b>4.14.36</b> rnorm</a></li>
<li class="chapter" data-level="4.14.37" data-path="base.html"><a href="base.html#weighted.mean"><i class="fa fa-check"></i><b>4.14.37</b> weighted.mean</a></li>
<li class="chapter" data-level="4.14.38" data-path="base.html"><a href="base.html#read.table"><i class="fa fa-check"></i><b>4.14.38</b> read.table</a></li>
<li class="chapter" data-level="4.14.39" data-path="base.html"><a href="base.html#write.table"><i class="fa fa-check"></i><b>4.14.39</b> write.table</a></li>
<li class="chapter" data-level="4.14.40" data-path="base.html"><a href="base.html#read.csv"><i class="fa fa-check"></i><b>4.14.40</b> read.csv</a></li>
<li class="chapter" data-level="4.14.41" data-path="base.html"><a href="base.html#write.csv"><i class="fa fa-check"></i><b>4.14.41</b> write.csv</a></li>
<li class="chapter" data-level="4.14.42" data-path="base.html"><a href="base.html#readrds"><i class="fa fa-check"></i><b>4.14.42</b> readRDS</a></li>
<li class="chapter" data-level="4.14.43" data-path="base.html"><a href="base.html#saverds"><i class="fa fa-check"></i><b>4.14.43</b> saveRDS</a></li>
<li class="chapter" data-level="4.14.44" data-path="base.html"><a href="base.html#jpeg-bmp-png-tiff"><i class="fa fa-check"></i><b>4.14.44</b> jpeg, bmp, png, tiff</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="gen.html"><a href="gen.html"><i class="fa fa-check"></i><b>5</b> Analisi di dati genetici</a><ul>
<li class="chapter" data-level="5.1" data-path="gen.html"><a href="gen.html#gen_intro"><i class="fa fa-check"></i><b>5.1</b> Introduzione</a><ul>
<li class="chapter" data-level="5.1.1" data-path="gen.html"><a href="gen.html#perché-la-genetica-con-r"><i class="fa fa-check"></i><b>5.1.1</b> Perché la genetica con R?</a></li>
<li class="chapter" data-level="5.1.2" data-path="gen.html"><a href="gen.html#risorse"><i class="fa fa-check"></i><b>5.1.2</b> Risorse</a></li>
<li class="chapter" data-level="5.1.3" data-path="gen.html"><a href="gen.html#prima-di-cominciare"><i class="fa fa-check"></i><b>5.1.3</b> Prima di cominciare…</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="gen.html"><a href="gen.html#gen_drift"><i class="fa fa-check"></i><b>5.2</b> Deriva Genetica</a></li>
<li class="chapter" data-level="5.3" data-path="gen.html"><a href="gen.html#gen_str"><i class="fa fa-check"></i><b>5.3</b> Struttura genetica delle popolazioni</a><ul>
<li class="chapter" data-level="5.3.1" data-path="gen.html"><a href="gen.html#le-statistiche-f"><i class="fa fa-check"></i><b>5.3.1</b> Le statistiche F</a></li>
<li class="chapter" data-level="5.3.2" data-path="gen.html"><a href="gen.html#inferenza-bayesiana-con-structure"><i class="fa fa-check"></i><b>5.3.2</b> Inferenza Bayesiana con STRUCTURE</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="gen.html"><a href="gen.html#gen_phylo"><i class="fa fa-check"></i><b>5.4</b> Filogenesi</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html"><i class="fa fa-check"></i><b>6</b> Machine learning in R</a><ul>
<li class="chapter" data-level="6.1" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#introduzione"><i class="fa fa-check"></i><b>6.1</b> Introduzione</a><ul>
<li class="chapter" data-level="6.1.1" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#supervised-learning"><i class="fa fa-check"></i><b>6.1.1</b> Supervised Learning</a></li>
<li class="chapter" data-level="6.1.2" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#unsupervised-learning"><i class="fa fa-check"></i><b>6.1.2</b> Unsupervised Learning</a></li>
<li class="chapter" data-level="6.1.3" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#dati"><i class="fa fa-check"></i><b>6.1.3</b> Dati</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#divisione-dei-dati"><i class="fa fa-check"></i><b>6.2</b> Divisione dei dati</a><ul>
<li class="chapter" data-level="6.2.1" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#campionamento-casuale-semplice"><i class="fa fa-check"></i><b>6.2.1</b> Campionamento casuale semplice</a></li>
<li class="chapter" data-level="6.2.2" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#campionamento-stratificato"><i class="fa fa-check"></i><b>6.2.2</b> Campionamento stratificato</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#metodi-di-ricampionamento"><i class="fa fa-check"></i><b>6.3</b> Metodi di ricampionamento</a><ul>
<li class="chapter" data-level="6.3.1" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#cross-validation"><i class="fa fa-check"></i><b>6.3.1</b> Cross-validation</a></li>
<li class="chapter" data-level="6.3.2" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#bootstrapping"><i class="fa fa-check"></i><b>6.3.2</b> Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#stima-della-performance-del-modello"><i class="fa fa-check"></i><b>6.4</b> Stima della performance del modello</a><ul>
<li class="chapter" data-level="6.4.1" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#modelli-di-regressione"><i class="fa fa-check"></i><b>6.4.1</b> Modelli di regressione</a></li>
<li class="chapter" data-level="6.4.2" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#modelli-di-classificazione"><i class="fa fa-check"></i><b>6.4.2</b> Modelli di classificazione</a></li>
<li class="chapter" data-level="6.4.3" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#concludendo"><i class="fa fa-check"></i><b>6.4.3</b> Concludendo…</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#algoritmi-di-machine-learning-in-r"><i class="fa fa-check"></i><b>6.5</b> Algoritmi di Machine Learning in R</a><ul>
<li class="chapter" data-level="6.5.1" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#decision-trees"><i class="fa fa-check"></i><b>6.5.1</b> Decision Trees</a></li>
<li class="chapter" data-level="6.5.2" data-path="machine-learning-in-r.html"><a href="machine-learning-in-r.html#random-forests"><i class="fa fa-check"></i><b>6.5.2</b> Random Forests</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Un viaggio nell’ambiente R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="gen" class="section level1">
<h1><span class="header-section-number">Capitolo 5</span> Analisi di dati genetici</h1>
<p><img src="Images/02-01.png" /></p>
<div id="gen_intro" class="section level2">
<h2><span class="header-section-number">5.1</span> Introduzione</h2>
<p>Nonostante il titolo, lo scopo di questo capitolo non è certo quello di insegnare la genetica! In effetti, quando si parla di genetica spesso ci si riferisce a quella branca della biologia (o della medicina) che ha a che fare con provette e pipette piuttosto che con la riga di comando! Se si è muniti di una fantasia particolarmente vivida la parola genetica ci fa venire in mente gli esperimenti di Jurassic Park per riportare in vita i dinosauri, o quelli che facevano nei laboratori dell’Umbrella Corporation e che hanno generato il temibilissimo T-Virus di Resident-Evil.</p>
<p>Tuttavia, un importante aspetto della genetica e delle sue applicazioni (come la genetica di popolazione, la genetica evoluzionistica o la genetica della conservazione) risiede proprio nell’analisi numerica. Se non siete convinti di questa affermazione pensate solo al fatto che <a href="https://en.wikipedia.org/wiki/Gregor_Mendel">Gregor Mendel</a>, uno dei padri della genetica, teorizzò la presenza di unità ereditarie (i geni) basandosi solo sull’osservazione e sul conteggio di piselli di diversa forma e colore! E, di certo, non aveva nessun computer che lo aiutasse a tenere i conti o ad organizzare i dati o a fare simulazioni! Proprio per questo <em>R</em> può diventare un ottimo alleato per aiutarci a capire meglio e ad analizzare anche i dati di tipo genetico.</p>
<div id="perché-la-genetica-con-r" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Perché la genetica con R?</h3>
<p>Nel suo libro dedicato alle analisi filogenetiche Emmanuel Paradis evidenzia alcune caratteristiche che fanno di <em>R</em> uno strumento di analisi per i dati genetici molto valido <span class="citation">(Paradis <a href="#ref-Paradis2012" role="doc-biblioref">2012</a>)</span>.</p>
<ul>
<li><strong>Integrazione</strong>
<ul>
<li>i dati genetici sono di diversa natura. Se questo potrebbe rappresentare un problema per altri softwares di analisi, di sicuro non lo è per <em>R</em>. I nostri dati, che si tratti di sequenze, di polimorfismi singoli, o di un altro tipo di <em>tipizzazione</em> genetica, possono essere organizzati nelle diverse classi di dati che <em>R</em> ci mette a disposizione;</li>
</ul></li>
<li><strong>Interattività</strong>
<ul>
<li>i nostri dati diventano un oggetto con il quale è possibile interagire a qualsiasi stadio della nostra analisi, per non perdere traccia di quello che sta succedendo “dietro le quinte”;</li>
</ul></li>
<li><strong>Programmabilità</strong>
<ul>
<li>possiamo adattare le nostre esigenze di analisi creandoci test e analisi <em>ad-hoc</em>. In questo modo non sarà più necessario dover continuamente cambiare software di analisi, ma potremmo svolgere il nostro lavoro dall’inizio alla fine all’interno dello stesso ambiente;</li>
</ul></li>
<li><strong>Evolvibilità</strong>
<ul>
<li>proprio come il mondo biologico intorno a noi, <em>R</em> è un ambiente in continua evoluzione. Questo continuo processo evolutivo consente di accomodare l’evolversi del tipo di analisi che stiamo applicando ai nostri dati.</li>
</ul></li>
</ul>
<p>Per uno studioso o un ricercatore laspetto dell’ <strong>Interattività</strong> è fondamentale! La possibilità di vedere e modificare i dati in qualsiasi momento dell’analisi permette anche di sviluppare e confutare ipotesi teoriche e modelli che hanno contribuito alla generazione dei dati stessi.</p>
</div>
<div id="risorse" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Risorse</h3>
<p>Altro punto di forza delle analisi genetiche con <em>R</em> è che si può contare sull’aiuto di una comunità in costante crescita ed evoluzione. Sono numerosissimi i pacchetti disponibili per le analisi più variegate (<a href="https://cran.r-project.org/web/views/Genetics.html">qui</a> e <a href="http://www.bioconductor.org">qui</a> trovate una lista, ragionevolmente aggiornata, ma non esaustiva, di pacchetti e risorse disponibili). Funzioni singole per effettuare analisi specifiche sono spesso disponibili su <a href="https://github.com">GitHub</a> e vengono distribuite e aggiornate dai diversi autori e collaboratori. Quindi non preoccupatevi se all’inizio vi sentite disorientati e non sapete bene come maneggiare i vostri dati genetici. Come spesso accade, lo stesso problema che dovrete risolvere sarà probabilmente capitato a qualcuno prima di voi, quindi, se proprio non riuscite a venirne a capo per conto vostro, non disperate e affinate le vostre capacitá di ricerca sui vari motori di ricerca o su <a href="https://stackoverflow.com">StackOverflow</a>.</p>
</div>
<div id="prima-di-cominciare" class="section level3">
<h3><span class="header-section-number">5.1.3</span> Prima di cominciare…</h3>
<p>In questo capitolo non possiamo certo aspettarci di imparare a svolgere tutte le possibili analisi genetiche in <em>R</em>. Daremo, piuttosto, uno sguardo d’insieme ad alcuni dei meccanismi fondamentali che sono alla base delle analisi di genetica di popolazione, ed impareremo a svolgere alcune delle analisi che generalmente costituiscono la base di partenza per studi più approfonditi. Per questo motivo è importante avere un minimo di familiarità con la terminologia fondamentale della genetica (allele, eterozigosi, popolazione, genotipo, gene, generazione, etc. etc. etc.). Quindi, se avete bisogno di rinfrescare la memoria, fatelo prima di incominciare quest’avventura.</p>
<p>Spesso i ricercatori cercano di rispondere a domande quali “Con quale frequenza un certo gene compare all’interno di un gruppo di individui?”; “Con quale probabilità la frequenza allelica rimarrà costante generazione dopo generazione?”; “Quali sono i fattori che alterano le frequenze geniche?”; “In quali regioni del genoma è più visibile l’effetto della selezione?”; “Che correlazione esiste tra la dimensione di una popolazione e la sua diversità genetica?”. Per rispondere a queste domande non si può prescindere dalla statistica e dal calcolo delle probabilità. Se avete bisogno di rinfrescare anche alcuni di questi concetti sarebbe bene farlo, ma se siete arrivati fino a qui nella lettura probabilmente avete già rinfrescato la vostra memoria.</p>
</div>
</div>
<div id="gen_drift" class="section level2">
<h2><span class="header-section-number">5.2</span> Deriva Genetica</h2>
<p>Uno dei concetti fondamentali della genetica di popolazione e, ad una scala più grande, dell’evoluzione è la <em>Deriva Genetica</em>. Immaginiamo di essere su una zattera alla deriva, in balia di vento e onde. Non sappiamo quando vedremo terra e neanche se il nostro approdo sarà un luogo più grande o più piccolo di quello da dove veniamo, più bello o più brutto, più ricco o più povero. Possiamo, però, essere ragionevolmente sicuri che, ovunque arriveremo, lo scenario che ci si presenterà sarà diverso da quello iniziale!</p>
<p>Il concetto di <em>Deriva Genetica</em> si ispira proprio a questo scenario alla Robinson Crusoe e si riferisce alla casuale selezione di gameti dall’insieme iniziale di geni di una popolazione. Se i gameti in una popolazione sono piccole zattere in mezzo al mare spinti solo da vento e onde, l’assortimento di gameti che arriveranno su un’isola per stabilire una nuova popolazione può essere paragonato ad un processo casuale che porterà alla formazione di una popolazione con caratteristiche diverse da quelle di origine.</p>
<div class="figure">
<img src="Images/02-02.png" alt="" />
<p class="caption">Albert Einstein diceva “Dio non gioca a dadi con l’universo.”, ma i fattori stocastici giocano un ruolo importantissimo nell’Evoluzione e nella Genetica di Popolazione.</p>
</div>
<p>Possiamo usare <em>R</em> e quello che abbiamo imparato fino ad ora per esplorare meglio questo concetto teorico e simularlo. Immaginiamo di lavorare con una popolazione di <span class="math inline">\(N\)</span> = 50 individui. Il genoma di questa specie è formato da 3 geni differenti che chiameremo gene <span class="math inline">\(A\)</span>, gene <span class="math inline">\(B\)</span> e gene <span class="math inline">\(C\)</span>. La specie è diploide, quindi ogni individuo possiede 2 copie per ogni gene. Poniamo anche che gli alleli (varianti dello stesso gene) per ogni gene sono solamente 2 che indicheremo con <span class="math inline">\(A_{1}\)</span> e <span class="math inline">\(A_{2}\)</span>, <span class="math inline">\(B_{1}\)</span> e <span class="math inline">\(B_{2}\)</span>, e <span class="math inline">\(C_{1}\)</span> e <span class="math inline">\(C_{2}\)</span>. Il numero totale di geni nella popolazione sarà quindi: <span class="math inline">\(N_{geni}\)</span> = 2 x 3 x 50 = 300. Infine, poniamo che le frequenze (<span class="math inline">\(p\)</span>) iniziali di ognuno degli alleli per ogni gene sono identiche con <span class="math inline">\(p_{A_{1}}\)</span> = <span class="math inline">\(p_{A_{2}}\)</span> = <span class="math inline">\(p_{B_{1}}\)</span> = <span class="math inline">\(p_{B_{2}}\)</span> = <span class="math inline">\(p_{C_{1}}\)</span> = <span class="math inline">\(p_{C_{2}}\)</span> = 0.5.</p>
<p>Creiamo questa popolazione. Un approccio (ricordate che in <em>R</em> raramente c’è un solo approccio per fare le cose!) potrebbe essere il seguente. Sapendo a priori che il genoma dei nostri individui è formato da 3 geni ognuno con 2 alleli, e sapendo la frequenza di ognuno di questi alleli, possiamo organizzare i genotipi in una lista.</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="gen.html#cb385-1"></a><span class="co"># genotipo degli individui organizzato in una lista</span></span>
<span id="cb385-2"><a href="gen.html#cb385-2"></a><span class="co"># ogni elemento della lista si riferisce ad un gene</span></span>
<span id="cb385-3"><a href="gen.html#cb385-3"></a>pop.ls &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="st">&#39;gene A&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;A_1&quot;</span>, <span class="dv">50</span>),</span>
<span id="cb385-4"><a href="gen.html#cb385-4"></a>                            <span class="kw">rep</span>(<span class="st">&quot;A_2&quot;</span>, <span class="dv">50</span>)), </span>
<span id="cb385-5"><a href="gen.html#cb385-5"></a>               <span class="st">&#39;gene B&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;B_1&quot;</span>, <span class="dv">50</span>),</span>
<span id="cb385-6"><a href="gen.html#cb385-6"></a>                            <span class="kw">rep</span>(<span class="st">&quot;B_2&quot;</span>, <span class="dv">50</span>)),</span>
<span id="cb385-7"><a href="gen.html#cb385-7"></a>               <span class="st">&#39;gene C&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;C_1&quot;</span>, <span class="dv">50</span>),</span>
<span id="cb385-8"><a href="gen.html#cb385-8"></a>                            <span class="kw">rep</span>(<span class="st">&quot;C_2&quot;</span>, <span class="dv">50</span>)))</span></code></pre></div>
<p>Potremmo scegliere di riassumere le frequenze alleliche della popolazione utilizzando una normale tabella come quella qui sotto.</p>
<table style="width:51%;">
<colgroup>
<col width="13%" />
<col width="12%" />
<col width="12%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Alleli</th>
<th align="center">gene A</th>
<th align="center">gene B</th>
<th align="center">gene C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>A_1</strong></td>
<td align="center">0.5</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>A_2</strong></td>
<td align="center">0.5</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>B_1</strong></td>
<td align="center">0</td>
<td align="center">0.5</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>B_2</strong></td>
<td align="center">0</td>
<td align="center">0.5</td>
<td align="center">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>C_1</strong></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0.5</td>
</tr>
<tr class="even">
<td align="center"><strong>C_2</strong></td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0.5</td>
</tr>
</tbody>
</table>
<p>Lavorando un po’ con i nostri dati possiamo però trovare una soluzione più intuitiva per visualizzare la distribuzione delle frequenze alleliche nella nostra popolazione, magari in una mamiera che renda anche semplice vedere la variazione delle frequenze da una generazione all’altra.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="gen.html#cb386-1"></a><span class="co"># trasformiamo la lista in un data frame</span></span>
<span id="cb386-2"><a href="gen.html#cb386-2"></a>pop.df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Gene =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;gene A&quot;</span>, <span class="dv">100</span>), </span>
<span id="cb386-3"><a href="gen.html#cb386-3"></a>                              <span class="kw">rep</span>(<span class="st">&quot;gene B&quot;</span>, <span class="dv">100</span>),</span>
<span id="cb386-4"><a href="gen.html#cb386-4"></a>                              <span class="kw">rep</span>(<span class="st">&quot;gene C&quot;</span>, <span class="dv">100</span>)),</span>
<span id="cb386-5"><a href="gen.html#cb386-5"></a>                     <span class="dt">Alleles =</span> <span class="kw">matrix</span>(<span class="kw">unlist</span>(pop.ls),</span>
<span id="cb386-6"><a href="gen.html#cb386-6"></a>                                      <span class="dt">ncol =</span> <span class="dv">1</span>, </span>
<span id="cb386-7"><a href="gen.html#cb386-7"></a>                                      <span class="dt">byrow=</span>F))</span>
<span id="cb386-8"><a href="gen.html#cb386-8"></a></span>
<span id="cb386-9"><a href="gen.html#cb386-9"></a><span class="co"># tabuliamo le frequenze alleliche</span></span>
<span id="cb386-10"><a href="gen.html#cb386-10"></a>f_tab &lt;-<span class="st"> </span><span class="kw">table</span>(pop.df<span class="op">$</span>Allele, pop.df<span class="op">$</span>Gene)<span class="op">/</span><span class="kw">nrow</span>(pop.df[pop.df<span class="op">$</span>Gene <span class="op">==</span><span class="st"> &quot;gene A&quot;</span>,])</span>
<span id="cb386-11"><a href="gen.html#cb386-11"></a></span>
<span id="cb386-12"><a href="gen.html#cb386-12"></a><span class="co"># utilizziamo i dati tabulati per creare un plot a barre </span></span>
<span id="cb386-13"><a href="gen.html#cb386-13"></a><span class="kw">barplot</span>(f_tab,</span>
<span id="cb386-14"><a href="gen.html#cb386-14"></a>        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;#14B635&quot;</span>, <span class="st">&quot;#158A29&quot;</span>,</span>
<span id="cb386-15"><a href="gen.html#cb386-15"></a>                <span class="st">&quot;#23A9F6&quot;</span>, <span class="st">&quot;#2970A1&quot;</span>,</span>
<span id="cb386-16"><a href="gen.html#cb386-16"></a>                <span class="st">&quot;#F77023&quot;</span>, <span class="st">&quot;#AF4E18&quot;</span>), </span>
<span id="cb386-17"><a href="gen.html#cb386-17"></a>  <span class="dt">xlab =</span> <span class="st">&quot;&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Frequenze alleliche&quot;</span>,</span>
<span id="cb386-18"><a href="gen.html#cb386-18"></a>  <span class="dt">axes =</span> F)</span>
<span id="cb386-19"><a href="gen.html#cb386-19"></a><span class="kw">axis</span>(<span class="dt">side =</span> <span class="dv">2</span>, </span>
<span id="cb386-20"><a href="gen.html#cb386-20"></a>     <span class="dt">labels =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb386-21"><a href="gen.html#cb386-21"></a>     <span class="dt">at =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb386-22"><a href="gen.html#cb386-22"></a><span class="kw">lines</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="fl">0.06</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="fl">3.6</span>),</span>
<span id="cb386-23"><a href="gen.html#cb386-23"></a>      <span class="dt">y =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb386-24"><a href="gen.html#cb386-24"></a>      <span class="dt">lty =</span> <span class="dv">2</span>, </span>
<span id="cb386-25"><a href="gen.html#cb386-25"></a>      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb386-26"><a href="gen.html#cb386-26"></a><span class="kw">par</span>(<span class="dt">xpd =</span> <span class="ot">TRUE</span>)</span>
<span id="cb386-27"><a href="gen.html#cb386-27"></a><span class="kw">legend</span>(<span class="fl">3.6</span>, <span class="dv">1</span>, </span>
<span id="cb386-28"><a href="gen.html#cb386-28"></a>       <span class="kw">c</span>(<span class="kw">expression</span>(<span class="kw">italic</span>(A)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(A)[<span class="dv">2</span>]),</span>
<span id="cb386-29"><a href="gen.html#cb386-29"></a>         <span class="kw">expression</span>(<span class="kw">italic</span>(B)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(B)[<span class="dv">2</span>]),</span>
<span id="cb386-30"><a href="gen.html#cb386-30"></a>         <span class="kw">expression</span>(<span class="kw">italic</span>(C)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(C)[<span class="dv">2</span>])),</span>
<span id="cb386-31"><a href="gen.html#cb386-31"></a>       <span class="dt">pch =</span> <span class="kw">rep</span>(<span class="dv">19</span>, <span class="dv">4</span>), </span>
<span id="cb386-32"><a href="gen.html#cb386-32"></a>       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;#14B635&quot;</span>, <span class="st">&quot;#158A29&quot;</span>,</span>
<span id="cb386-33"><a href="gen.html#cb386-33"></a>               <span class="st">&quot;#23A9F6&quot;</span>, <span class="st">&quot;#2970A1&quot;</span>,</span>
<span id="cb386-34"><a href="gen.html#cb386-34"></a>               <span class="st">&quot;#F77023&quot;</span>, <span class="st">&quot;#AF4E18&quot;</span>),</span>
<span id="cb386-35"><a href="gen.html#cb386-35"></a>       <span class="dt">horiz =</span> F, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/drift_01_1-1.png" width="672" /></p>
<p>Questa rappresentazione grafica mostra chiaramente le frequenze alleliche iniziali della popolazione. La linea rossa tratteggiata attraversa le tre barre colorate e le taglia esattamente al valore di 0.5, la frequenza che avevamo stabilito. Cosa succede dopo una generazione in cui la deriva genetica è la sola forza che agisce sulle frequenza geniche? In altre parole, campionando a caso come cambiano le frequenze alleliche nella generazione successiva? La funzione <code>sample()</code> fa al caso nostro perché ci permette di simulare il campionamento casuale e la deriva dei geni all’interno della popolazione.</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="gen.html#cb387-1"></a><span class="co"># per ottenere gli stessi risultati dell&#39;esempio</span></span>
<span id="cb387-2"><a href="gen.html#cb387-2"></a><span class="kw">set.seed</span>(<span class="dv">482</span>)</span>
<span id="cb387-3"><a href="gen.html#cb387-3"></a></span>
<span id="cb387-4"><a href="gen.html#cb387-4"></a><span class="co"># campioniamo ogni elemento della lista (ogni gene) 100 volte</span></span>
<span id="cb387-5"><a href="gen.html#cb387-5"></a><span class="co"># ammettiamo il replacement degli alleli</span></span>
<span id="cb387-6"><a href="gen.html#cb387-6"></a>pop.ls.t1 &lt;-<span class="st"> </span><span class="kw">lapply</span>(pop.ls, sample, <span class="dv">100</span>, <span class="dt">replace =</span> T)</span></code></pre></div>
<p>Adesso riproduciamo il codice per creare un nuovo grafico aggiornato con le frequenze alleliche della nuova generazione.</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="gen.html#cb388-1"></a><span class="co"># trasformiamo la lista in un data frame</span></span>
<span id="cb388-2"><a href="gen.html#cb388-2"></a>pop.df.t1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Gene =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;gene A&quot;</span>, <span class="dv">100</span>),</span>
<span id="cb388-3"><a href="gen.html#cb388-3"></a>                                 <span class="kw">rep</span>(<span class="st">&quot;gene B&quot;</span>, <span class="dv">100</span>),</span>
<span id="cb388-4"><a href="gen.html#cb388-4"></a>                                 <span class="kw">rep</span>(<span class="st">&quot;gene C&quot;</span>, <span class="dv">100</span>)),</span>
<span id="cb388-5"><a href="gen.html#cb388-5"></a>                     <span class="dt">Alleles =</span> <span class="kw">matrix</span>(<span class="kw">unlist</span>(pop.ls.t1), <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">byrow=</span>F))</span>
<span id="cb388-6"><a href="gen.html#cb388-6"></a></span>
<span id="cb388-7"><a href="gen.html#cb388-7"></a><span class="co"># tabuliamo e per creiamo il plot a barre </span></span>
<span id="cb388-8"><a href="gen.html#cb388-8"></a><span class="kw">barplot</span>(<span class="kw">table</span>(pop.df.t1<span class="op">$</span>Allele,</span>
<span id="cb388-9"><a href="gen.html#cb388-9"></a>              pop.df.t1<span class="op">$</span>Gene)<span class="op">/</span><span class="kw">nrow</span>(pop.df.t1[pop.df.t1<span class="op">$</span>Gene <span class="op">==</span><span class="st"> &quot;gene A&quot;</span>,]),</span>
<span id="cb388-10"><a href="gen.html#cb388-10"></a>        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;#14B635&quot;</span>, <span class="st">&quot;#158A29&quot;</span>,</span>
<span id="cb388-11"><a href="gen.html#cb388-11"></a>                <span class="st">&quot;#23A9F6&quot;</span>, <span class="st">&quot;#2970A1&quot;</span>,</span>
<span id="cb388-12"><a href="gen.html#cb388-12"></a>                <span class="st">&quot;#F77023&quot;</span>, <span class="st">&quot;#AF4E18&quot;</span> ),</span>
<span id="cb388-13"><a href="gen.html#cb388-13"></a>        <span class="dt">xlab=</span><span class="st">&quot;&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Frequenze alleliche&quot;</span>, <span class="dt">axes =</span> F)</span>
<span id="cb388-14"><a href="gen.html#cb388-14"></a><span class="kw">axis</span>(<span class="dt">side =</span> <span class="dv">2</span>, <span class="dt">labels =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb388-15"><a href="gen.html#cb388-15"></a>     <span class="dt">at =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb388-16"><a href="gen.html#cb388-16"></a><span class="kw">lines</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="fl">0.06</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="fl">3.6</span>), <span class="dt">y =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb388-17"><a href="gen.html#cb388-17"></a>      <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb388-18"><a href="gen.html#cb388-18"></a><span class="kw">par</span>(<span class="dt">xpd=</span><span class="ot">TRUE</span>)</span>
<span id="cb388-19"><a href="gen.html#cb388-19"></a><span class="kw">legend</span>(<span class="fl">3.6</span>, <span class="dv">1</span>, </span>
<span id="cb388-20"><a href="gen.html#cb388-20"></a>       <span class="kw">c</span>(<span class="kw">expression</span>(<span class="kw">italic</span>(A)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(A)[<span class="dv">2</span>]),</span>
<span id="cb388-21"><a href="gen.html#cb388-21"></a>         <span class="kw">expression</span>(<span class="kw">italic</span>(B)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(B)[<span class="dv">2</span>]),</span>
<span id="cb388-22"><a href="gen.html#cb388-22"></a>         <span class="kw">expression</span>(<span class="kw">italic</span>(C)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(C)[<span class="dv">2</span>])),</span>
<span id="cb388-23"><a href="gen.html#cb388-23"></a>       <span class="dt">pch =</span> <span class="kw">rep</span>(<span class="dv">19</span>, <span class="dv">4</span>), </span>
<span id="cb388-24"><a href="gen.html#cb388-24"></a>       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;#14B635&quot;</span>, <span class="st">&quot;#158A29&quot;</span>,</span>
<span id="cb388-25"><a href="gen.html#cb388-25"></a>               <span class="st">&quot;#23A9F6&quot;</span>, <span class="st">&quot;#2970A1&quot;</span>,</span>
<span id="cb388-26"><a href="gen.html#cb388-26"></a>               <span class="st">&quot;#F77023&quot;</span>, <span class="st">&quot;#AF4E18&quot;</span>),</span>
<span id="cb388-27"><a href="gen.html#cb388-27"></a>       <span class="dt">horiz =</span> F, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/drift_02_1-1.png" width="672" /></p>
<p>Dopo una sola generazione le frequenze sono cambiate! Tutti gli alleli nella nostra popolazione hanno subito una variazione. Questa variazione potrebbe non sembrare molto grande o comunque non particolarmente significativa, ma c’è. Possiamo chiaederci un’altra domanda. Cosa succede dopo 200 generazioni di variazione stocastica delle frequenze alleliche? Cerchiamo di visualizzare passo passo come le frequenze cambiano in relazione al passare del tempo.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="gen.html#cb389-1"></a><span class="kw">set.seed</span>(<span class="dv">23561</span>)</span>
<span id="cb389-2"><a href="gen.html#cb389-2"></a>geneA &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">mode =</span> <span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> <span class="dv">200</span>)</span>
<span id="cb389-3"><a href="gen.html#cb389-3"></a>geneB &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">mode =</span> <span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> <span class="dv">200</span>)</span>
<span id="cb389-4"><a href="gen.html#cb389-4"></a>geneC &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">mode =</span> <span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> <span class="dv">200</span>)</span>
<span id="cb389-5"><a href="gen.html#cb389-5"></a>geneA[[<span class="dv">1</span>]] &lt;-<span class="st"> </span>pop.ls[[<span class="dv">1</span>]]</span>
<span id="cb389-6"><a href="gen.html#cb389-6"></a>geneB[[<span class="dv">1</span>]] &lt;-<span class="st"> </span>pop.ls[[<span class="dv">2</span>]]</span>
<span id="cb389-7"><a href="gen.html#cb389-7"></a>geneC[[<span class="dv">1</span>]] &lt;-<span class="st"> </span>pop.ls[[<span class="dv">3</span>]]</span>
<span id="cb389-8"><a href="gen.html#cb389-8"></a></span>
<span id="cb389-9"><a href="gen.html#cb389-9"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span><span class="dv">200</span>) {</span>
<span id="cb389-10"><a href="gen.html#cb389-10"></a>  geneA[[i]] &lt;-<span class="st"> </span><span class="kw">sample</span>(geneA[[i<span class="dv">-1</span>]], <span class="dv">100</span>, <span class="dt">replace =</span> T)</span>
<span id="cb389-11"><a href="gen.html#cb389-11"></a>  geneB[[i]] &lt;-<span class="st"> </span><span class="kw">sample</span>(geneB[[i<span class="dv">-1</span>]], <span class="dv">100</span>, <span class="dt">replace =</span> T)</span>
<span id="cb389-12"><a href="gen.html#cb389-12"></a>  geneC[[i]] &lt;-<span class="st"> </span><span class="kw">sample</span>(geneC[[i<span class="dv">-1</span>]], <span class="dv">100</span>, <span class="dt">replace =</span> T)</span>
<span id="cb389-13"><a href="gen.html#cb389-13"></a>}</span>
<span id="cb389-14"><a href="gen.html#cb389-14"></a></span>
<span id="cb389-15"><a href="gen.html#cb389-15"></a>freqA &lt;-<span class="st"> </span><span class="ot">NULL</span></span>
<span id="cb389-16"><a href="gen.html#cb389-16"></a>freqa &lt;-<span class="st"> </span><span class="ot">NULL</span></span>
<span id="cb389-17"><a href="gen.html#cb389-17"></a>freqB &lt;-<span class="st"> </span><span class="ot">NULL</span></span>
<span id="cb389-18"><a href="gen.html#cb389-18"></a>freqb &lt;-<span class="st"> </span><span class="ot">NULL</span> </span>
<span id="cb389-19"><a href="gen.html#cb389-19"></a>freqC &lt;-<span class="st"> </span><span class="ot">NULL</span></span>
<span id="cb389-20"><a href="gen.html#cb389-20"></a>freqc &lt;-<span class="st"> </span><span class="ot">NULL</span> </span>
<span id="cb389-21"><a href="gen.html#cb389-21"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">200</span>) {</span>
<span id="cb389-22"><a href="gen.html#cb389-22"></a>  freqA[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(geneA[[i]] <span class="op">==</span><span class="st"> &quot;A_1&quot;</span>)<span class="op">/</span><span class="st"> </span><span class="kw">length</span>(geneA[[i]])</span>
<span id="cb389-23"><a href="gen.html#cb389-23"></a>  freqa[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(geneA[[i]] <span class="op">==</span><span class="st"> &quot;A_2&quot;</span>)<span class="op">/</span><span class="st"> </span><span class="kw">length</span>(geneA[[i]])</span>
<span id="cb389-24"><a href="gen.html#cb389-24"></a>  freqB[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(geneB[[i]] <span class="op">==</span><span class="st"> &quot;B_1&quot;</span>)<span class="op">/</span><span class="st"> </span><span class="kw">length</span>(geneB[[i]])</span>
<span id="cb389-25"><a href="gen.html#cb389-25"></a>  freqb[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(geneB[[i]] <span class="op">==</span><span class="st"> &quot;B_2&quot;</span>)<span class="op">/</span><span class="st"> </span><span class="kw">length</span>(geneB[[i]])</span>
<span id="cb389-26"><a href="gen.html#cb389-26"></a>  freqC[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(geneC[[i]] <span class="op">==</span><span class="st"> &quot;C_1&quot;</span>)<span class="op">/</span><span class="st"> </span><span class="kw">length</span>(geneC[[i]])</span>
<span id="cb389-27"><a href="gen.html#cb389-27"></a>  freqc[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(geneC[[i]] <span class="op">==</span><span class="st"> &quot;C_2&quot;</span>)<span class="op">/</span><span class="st"> </span><span class="kw">length</span>(geneC[[i]])</span>
<span id="cb389-28"><a href="gen.html#cb389-28"></a>}</span>
<span id="cb389-29"><a href="gen.html#cb389-29"></a></span>
<span id="cb389-30"><a href="gen.html#cb389-30"></a><span class="kw">plot</span>(<span class="dv">1</span>,<span class="dv">0</span>, <span class="dt">type=</span><span class="st">&quot;n&quot;</span>,</span>
<span id="cb389-31"><a href="gen.html#cb389-31"></a>     <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">200</span>),</span>
<span id="cb389-32"><a href="gen.html#cb389-32"></a>     <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb389-33"><a href="gen.html#cb389-33"></a>     <span class="dt">main =</span> <span class="st">&quot;Variazione frequenze alleliche nei geni A, B e C&quot;</span>,</span>
<span id="cb389-34"><a href="gen.html#cb389-34"></a>     <span class="dt">xlab=</span><span class="st">&quot;Generazioni&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Frequenze alleliche&quot;</span></span>
<span id="cb389-35"><a href="gen.html#cb389-35"></a>     )</span>
<span id="cb389-36"><a href="gen.html#cb389-36"></a><span class="kw">points</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>, freqA, <span class="dt">pch =</span> <span class="dv">21</span>, <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bg =</span> <span class="st">&quot;#14B635&quot;</span>)</span>
<span id="cb389-37"><a href="gen.html#cb389-37"></a><span class="kw">points</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>, freqa, <span class="dt">pch =</span> <span class="dv">21</span>, <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bg =</span> <span class="st">&quot;#158A29&quot;</span>)</span>
<span id="cb389-38"><a href="gen.html#cb389-38"></a><span class="kw">points</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>, freqB, <span class="dt">pch =</span> <span class="dv">21</span>, <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bg =</span> <span class="st">&quot;#23A9F6&quot;</span>)</span>
<span id="cb389-39"><a href="gen.html#cb389-39"></a><span class="kw">points</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>, freqb, <span class="dt">pch =</span> <span class="dv">21</span>, <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bg =</span> <span class="st">&quot;#2970A1&quot;</span>)</span>
<span id="cb389-40"><a href="gen.html#cb389-40"></a><span class="kw">points</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>, freqC, <span class="dt">pch =</span> <span class="dv">21</span>, <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bg =</span> <span class="st">&quot;#F77023&quot;</span>)</span>
<span id="cb389-41"><a href="gen.html#cb389-41"></a><span class="kw">points</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>, freqc, <span class="dt">pch =</span> <span class="dv">21</span>, <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bg =</span> <span class="st">&quot;#AF4E18&quot;</span>)</span>
<span id="cb389-42"><a href="gen.html#cb389-42"></a><span class="kw">par</span>(<span class="dt">xpd=</span><span class="ot">TRUE</span>)</span>
<span id="cb389-43"><a href="gen.html#cb389-43"></a><span class="kw">legend</span>(<span class="dv">180</span>, <span class="fl">.75</span>, </span>
<span id="cb389-44"><a href="gen.html#cb389-44"></a>       <span class="kw">c</span>(<span class="kw">expression</span>(<span class="kw">italic</span>(A)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(A)[<span class="dv">2</span>]),</span>
<span id="cb389-45"><a href="gen.html#cb389-45"></a>         <span class="kw">expression</span>(<span class="kw">italic</span>(B)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(B)[<span class="dv">2</span>]),</span>
<span id="cb389-46"><a href="gen.html#cb389-46"></a>         <span class="kw">expression</span>(<span class="kw">italic</span>(C)[<span class="dv">1</span>]), <span class="kw">expression</span>(<span class="kw">italic</span>(C)[<span class="dv">2</span>])),</span>
<span id="cb389-47"><a href="gen.html#cb389-47"></a>       <span class="dt">pch =</span> <span class="kw">rep</span>(<span class="dv">19</span>, <span class="dv">4</span>), <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;#14B635&quot;</span>, <span class="st">&quot;#158A29&quot;</span>,</span>
<span id="cb389-48"><a href="gen.html#cb389-48"></a>                                 <span class="st">&quot;#23A9F6&quot;</span>, <span class="st">&quot;#2970A1&quot;</span>,</span>
<span id="cb389-49"><a href="gen.html#cb389-49"></a>                                 <span class="st">&quot;#F77023&quot;</span>, <span class="st">&quot;#AF4E18&quot;</span> ),</span>
<span id="cb389-50"><a href="gen.html#cb389-50"></a>       <span class="dt">horiz =</span> F, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/drift_03-1.png" width="672" /></p>
<p>Il blocco di codice appena eseguito simula lo scorrere del tempo per la nostra popolazione (200 generazioni). Il grafico mostra la naturale (e stocastica) oscillazione delle frequenze geniche al passare delle generazioni. È interessante notare come dopo circa 150 generazioni l’allele <span class="math inline">\(C_{2}\)</span> va a fissazione (<span class="math inline">\(p_{C_{2}}\)</span> = 1), mentre l’allele <span class="math inline">\(C_{1}\)</span> si estingue dalla popolazione (<span class="math inline">\(p_{C_{1}}\)</span> = 0). Gli alleli degli altri due geni continuano ad oscillare e per capire quanto tempo ci vuole affinchè arrivino a fissazione/estinzione bisgnorebbe continuare la simulazione.</p>
<p>Un aspetto importante da tenere in considerazione quando parliamo di processi stocastici è che prendere una decisione operativa sulla base dei risultati di una singola simulazione potrebbe non avere molto senso. Se infatti provassimo ad ottenere un nuovo grafico delle frequenze alleliche a partire da un altro “seme” iniziale i risultati sarebbero differenti. Quello che possiamo fare è, quindi, riprovare a far correre la simulazione diverse volte, e calcolare i valori medi dei risultati. Ad esempio, un aspetto interessante in biologia evoluzionistica è la stima del tempo medio di fissazione di un allele in uno scenario in cui il solo motore che contribuisce alla variazione delle frequenze è la <em>Deriva Genetica</em>. Questo ci offre le basi per construire un’<strong>ipotesi nulla</strong> da poter confrontare con i dati reali e poterli meglio interpretare. Vediamo come costruire una distribuzione di tempi medi di fissazione da usare come ipotesi nulla.</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="gen.html#cb390-1"></a><span class="co"># Funzione per simulare il tempo medio di fissazione degli alleli</span></span>
<span id="cb390-2"><a href="gen.html#cb390-2"></a></span>
<span id="cb390-3"><a href="gen.html#cb390-3"></a><span class="co"># pop.ls = Lista. Ogni elemento contiene i geni della popolazione</span></span>
<span id="cb390-4"><a href="gen.html#cb390-4"></a><span class="co"># num.sim = Numero di iterazioni della simulazione </span></span>
<span id="cb390-5"><a href="gen.html#cb390-5"></a>sim.gen2fix &lt;-<span class="st"> </span><span class="cf">function</span> (pop.ls, num.sims) {</span>
<span id="cb390-6"><a href="gen.html#cb390-6"></a>  </span>
<span id="cb390-7"><a href="gen.html#cb390-7"></a>  <span class="co"># Numero totale di loci per ogni gene nella popolazione  </span></span>
<span id="cb390-8"><a href="gen.html#cb390-8"></a>  n &lt;-<span class="st"> </span><span class="kw">length</span>(pop.ls[[<span class="dv">1</span>]])</span>
<span id="cb390-9"><a href="gen.html#cb390-9"></a>  <span class="co"># Numero di geni differenti nella popolazione</span></span>
<span id="cb390-10"><a href="gen.html#cb390-10"></a>  n.genes &lt;-<span class="st"> </span><span class="kw">length</span>(pop.ls)</span>
<span id="cb390-11"><a href="gen.html#cb390-11"></a>  <span class="co"># Creo una lista vuota per contenere i risultati della simulazione.</span></span>
<span id="cb390-12"><a href="gen.html#cb390-12"></a>  <span class="co"># Il numero di elementi è pari al numero di geni diversi.</span></span>
<span id="cb390-13"><a href="gen.html#cb390-13"></a>  <span class="co"># Ogni elemento è un vettore di lunghezza pari al numero di simulazioni.</span></span>
<span id="cb390-14"><a href="gen.html#cb390-14"></a>  generations &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">mode =</span> <span class="st">&quot;list&quot;</span>, <span class="dt">length =</span> <span class="kw">length</span>(pop.ls))</span>
<span id="cb390-15"><a href="gen.html#cb390-15"></a>  <span class="cf">for</span> (h <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n.genes){</span>
<span id="cb390-16"><a href="gen.html#cb390-16"></a>    generations[[h]] &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, num.sims)</span>
<span id="cb390-17"><a href="gen.html#cb390-17"></a>  }</span>
<span id="cb390-18"><a href="gen.html#cb390-18"></a>  <span class="kw">names</span>(generations) &lt;-<span class="st"> </span><span class="kw">names</span>(pop.ls)</span>
<span id="cb390-19"><a href="gen.html#cb390-19"></a>  </span>
<span id="cb390-20"><a href="gen.html#cb390-20"></a>  <span class="co"># Ciclo di simulazione </span></span>
<span id="cb390-21"><a href="gen.html#cb390-21"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>num.sims) {</span>
<span id="cb390-22"><a href="gen.html#cb390-22"></a>    temp.pop.ls &lt;-<span class="st"> </span>pop.ls</span>
<span id="cb390-23"><a href="gen.html#cb390-23"></a>    <span class="cf">for</span> (y <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n.genes) {</span>
<span id="cb390-24"><a href="gen.html#cb390-24"></a>      <span class="cf">while</span> (<span class="kw">max</span>(<span class="kw">table</span>(temp.pop.ls[[y]])) <span class="op">&lt;</span><span class="st"> </span>n) {</span>
<span id="cb390-25"><a href="gen.html#cb390-25"></a>        temp.pop.ls[[y]] &lt;-<span class="st"> </span><span class="kw">sample</span>(temp.pop.ls[[y]], <span class="dv">100</span>, <span class="dt">replace =</span> T)</span>
<span id="cb390-26"><a href="gen.html#cb390-26"></a>        generations[[y]][i] &lt;-<span class="st"> </span>generations[[y]][i] <span class="op">+</span><span class="st"> </span><span class="dv">1</span></span>
<span id="cb390-27"><a href="gen.html#cb390-27"></a>      }</span>
<span id="cb390-28"><a href="gen.html#cb390-28"></a>    }</span>
<span id="cb390-29"><a href="gen.html#cb390-29"></a>  }</span>
<span id="cb390-30"><a href="gen.html#cb390-30"></a>  </span>
<span id="cb390-31"><a href="gen.html#cb390-31"></a>  <span class="co"># Statistiche descrittive dei risultati</span></span>
<span id="cb390-32"><a href="gen.html#cb390-32"></a>  df &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">data.frame</span>(<span class="kw">lapply</span>(generations, mean)),</span>
<span id="cb390-33"><a href="gen.html#cb390-33"></a>        <span class="kw">data.frame</span>(<span class="kw">lapply</span>(generations, sd))) </span>
<span id="cb390-34"><a href="gen.html#cb390-34"></a>  <span class="kw">rownames</span>(df) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;sd&quot;</span>)</span>
<span id="cb390-35"><a href="gen.html#cb390-35"></a></span>
<span id="cb390-36"><a href="gen.html#cb390-36"></a>  <span class="co"># Ciclo per plottare i risultati</span></span>
<span id="cb390-37"><a href="gen.html#cb390-37"></a>  <span class="co"># Da modificare se i geni da plottare sono &gt; 3</span></span>
<span id="cb390-38"><a href="gen.html#cb390-38"></a>  <span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb390-39"><a href="gen.html#cb390-39"></a>  <span class="cf">for</span> (z <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n.genes) {</span>
<span id="cb390-40"><a href="gen.html#cb390-40"></a>    graph &lt;-<span class="st"> </span>generations[[z]]</span>
<span id="cb390-41"><a href="gen.html#cb390-41"></a>    <span class="kw">hist</span>(graph, <span class="dt">main =</span> <span class="kw">paste</span>(<span class="st">&quot;Num. medio di Generazioni per </span><span class="ch">\n</span><span class="st">fissazione &quot;</span>,</span>
<span id="cb390-42"><a href="gen.html#cb390-42"></a>                             <span class="kw">names</span>(generations[z])),</span>
<span id="cb390-43"><a href="gen.html#cb390-43"></a>         <span class="dt">xlab =</span> <span class="st">&quot;Generazioni&quot;</span>)</span>
<span id="cb390-44"><a href="gen.html#cb390-44"></a>    <span class="kw">abline</span>(<span class="dt">v =</span> df[<span class="dv">1</span>,z], <span class="dt">col =</span> <span class="st">&quot;orange&quot;</span>, <span class="dt">lwd =</span> <span class="fl">1.5</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</span>
<span id="cb390-45"><a href="gen.html#cb390-45"></a>  }</span>
<span id="cb390-46"><a href="gen.html#cb390-46"></a>  <span class="kw">return</span>(df)</span>
<span id="cb390-47"><a href="gen.html#cb390-47"></a>}</span>
<span id="cb390-48"><a href="gen.html#cb390-48"></a></span>
<span id="cb390-49"><a href="gen.html#cb390-49"></a><span class="kw">sim.gen2fix</span>(pop.ls, <span class="dv">1000</span>)</span></code></pre></div>
<pre><code>##         gene.A  gene.B    gene.C
## mean 135.23800 139.435 133.83200
## sd    99.41759 102.342  97.99392</code></pre>
<p><img src="02-gen_files/figure-html/drift_04-1.png" width="672" /></p>
<p>I dati che abbiamo simulato ci dicono che in media ci vogliono circa 135 generazioni prima che uno dei due alleli vada a fissazione. Ovviamente questo è uno scenario estremamente semplificato, ma permette comunque di avere un’ipotesi nulla da usare per la verifica di dati sperimentali.</p>
<p>Immaginiamo di trasferirci in laboratorio. Vogliamo verificare sperimentalmente se le fluttuazioni delle frequenze alleliche osservate in diverse colture di moscerini sono dovute al caso o sono invece dovute alla forza selettiva applicata da diversi ambienti nei quali le nostro colonie sono cresciute. Anche qui, per facilitare la comprensione del meccanismo, ci soffermeremo su popolazioni di 500 individui con 3 geni diploidi. Per prima casa simuliamo la popolazione sorgente che nasce e scresce in un ambiente privo di selezione.</p>
<p><img src="02-gen_files/figure-html/drift_05-1.png" width="672" /></p>
<p>Cosa succede se non lasciamo che sia solo il caso a guidare la variazione delle frequenze alleliche? In altre parole, cosa succede quando applichiamo una pressione selettiva che favorisce alcuni geni/alleli rispetto ad altri? Per semplicità svolgeremo questa procedura su uno solo dei 3 geni e visualizzeremo come le frequenze cambiano al variare del coefficiente di selezione.</p>
<p><img src="02-gen_files/figure-html/drift_05_b-1.png" width="672" /></p>
<p>È evidente che tanto più intensa è la pressione selettiva tanto più rapidamente gli alleli andranno a fissazione. A questo punto possiamo porre un’altra domanda interessante: ammettendo che sia solo la deriva genetica a produrre un cambiamento nelle frequenze alleliche della popolazione, che effetto hanno parmentri come la dimensione della popolazione e la frequenza allelica iniziale sulla stima del tempo medio di fissazione dei diversi geni? Intuitivamente, possiamo immaginare che entrambi i fattori possano avere un ruolo nell’influenzare il tempo medio di fissazione di un gene. La relazione matematica formale che tiene insieme tutte queste variabili e che descrive la loro interazione è evidenziata nella seguente equazione dove <span class="math inline">\(t_{fix}\)</span> è il tempo (generalmente espresso in numero di generazioni) necessario alla fissazinoe di un allele, <span class="math inline">\(N_{e}\)</span> è la <a href="https://en.wikipedia.org/wiki/Effective_population_size">dimensione effettiva della popolazione</a> e <span class="math inline">\(p\)</span> è la frequenza allelica.</p>
<p><span class="math display">\[t_{fix} = \frac{-4N_e(1-p)log(1-p)}{p}\]</span></p>
<p>Come al solito, cerchiamo di ottenere una rappresentazione grafica di questo processo e costruiamo un grafico in cui visualizziamo l’output di questa equazione con diversi valori di <span class="math inline">\(p\)</span> e di <span class="math inline">\(N_{e}\)</span>.</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="gen.html#cb392-1"></a><span class="co"># per visualizzare i numeri non in notazione scientifica</span></span>
<span id="cb392-2"><a href="gen.html#cb392-2"></a><span class="kw">options</span>(<span class="dt">scipen=</span><span class="dv">999</span>)</span>
<span id="cb392-3"><a href="gen.html#cb392-3"></a></span>
<span id="cb392-4"><a href="gen.html#cb392-4"></a><span class="co"># vettore con 4 differenti frequenze alleliche</span></span>
<span id="cb392-5"><a href="gen.html#cb392-5"></a>p &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>)</span>
<span id="cb392-6"><a href="gen.html#cb392-6"></a></span>
<span id="cb392-7"><a href="gen.html#cb392-7"></a><span class="co"># vettore con 10 differenti valori di dimensione effettiva di popolazione </span></span>
<span id="cb392-8"><a href="gen.html#cb392-8"></a>N &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>, <span class="dv">1000</span>, <span class="dv">5000</span>, <span class="dv">10000</span>, <span class="dv">25000</span>, <span class="dv">50000</span>, <span class="dv">100000</span>)</span>
<span id="cb392-9"><a href="gen.html#cb392-9"></a></span>
<span id="cb392-10"><a href="gen.html#cb392-10"></a><span class="co"># creo un data.frame con combinazione di tutti i valori</span></span>
<span id="cb392-11"><a href="gen.html#cb392-11"></a>df &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(p, N)</span>
<span id="cb392-12"><a href="gen.html#cb392-12"></a><span class="kw">colnames</span>(df) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;p&quot;</span>, <span class="st">&quot;N&quot;</span>)</span>
<span id="cb392-13"><a href="gen.html#cb392-13"></a></span>
<span id="cb392-14"><a href="gen.html#cb392-14"></a><span class="co"># aggiungo una colonna per contenere il valore del tempo di fissazione</span></span>
<span id="cb392-15"><a href="gen.html#cb392-15"></a>df<span class="op">$</span>tfix &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb392-16"><a href="gen.html#cb392-16"></a></span>
<span id="cb392-17"><a href="gen.html#cb392-17"></a><span class="co"># loop per applicare l&#39;equazione</span></span>
<span id="cb392-18"><a href="gen.html#cb392-18"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(df)) {</span>
<span id="cb392-19"><a href="gen.html#cb392-19"></a>  df[i, <span class="dv">3</span>] &lt;-<span class="st"> </span>((<span class="op">-</span><span class="dv">4</span><span class="op">*</span>df[i,<span class="dv">2</span>])<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>df[i,<span class="dv">1</span>])<span class="op">*</span><span class="kw">log</span>(<span class="dv">1</span><span class="op">-</span>df[i,<span class="dv">1</span>]))<span class="op">/</span>df[i,<span class="dv">1</span>]</span>
<span id="cb392-20"><a href="gen.html#cb392-20"></a>}</span>
<span id="cb392-21"><a href="gen.html#cb392-21"></a></span>
<span id="cb392-22"><a href="gen.html#cb392-22"></a><span class="co"># grafico</span></span>
<span id="cb392-23"><a href="gen.html#cb392-23"></a><span class="kw">plot</span>(df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.01</span>, <span class="st">&quot;N&quot;</span>], </span>
<span id="cb392-24"><a href="gen.html#cb392-24"></a>     df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.01</span>, <span class="st">&quot;tfix&quot;</span>],</span>
<span id="cb392-25"><a href="gen.html#cb392-25"></a>     <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,</span>
<span id="cb392-26"><a href="gen.html#cb392-26"></a>     <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb392-27"><a href="gen.html#cb392-27"></a>     <span class="dt">xlab =</span> <span class="st">&quot;Dimensione della popolazione&quot;</span>,</span>
<span id="cb392-28"><a href="gen.html#cb392-28"></a>     <span class="dt">ylab =</span> <span class="st">&quot;Tempo (Num. di Generazioni)&quot;</span>)</span>
<span id="cb392-29"><a href="gen.html#cb392-29"></a><span class="kw">lines</span>(df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.1</span>, <span class="st">&quot;N&quot;</span>], </span>
<span id="cb392-30"><a href="gen.html#cb392-30"></a>      df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.1</span>, <span class="st">&quot;tfix&quot;</span>],</span>
<span id="cb392-31"><a href="gen.html#cb392-31"></a>      <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,</span>
<span id="cb392-32"><a href="gen.html#cb392-32"></a>      <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>)</span>
<span id="cb392-33"><a href="gen.html#cb392-33"></a><span class="kw">lines</span>(df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.25</span>, <span class="st">&quot;N&quot;</span>], </span>
<span id="cb392-34"><a href="gen.html#cb392-34"></a>      df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.25</span>, <span class="st">&quot;tfix&quot;</span>],</span>
<span id="cb392-35"><a href="gen.html#cb392-35"></a>      <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,</span>
<span id="cb392-36"><a href="gen.html#cb392-36"></a>      <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb392-37"><a href="gen.html#cb392-37"></a><span class="kw">lines</span>(df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.5</span>, <span class="st">&quot;N&quot;</span>], </span>
<span id="cb392-38"><a href="gen.html#cb392-38"></a>      df[df<span class="op">$</span>p <span class="op">==</span><span class="st"> </span><span class="fl">0.5</span>, <span class="st">&quot;tfix&quot;</span>],</span>
<span id="cb392-39"><a href="gen.html#cb392-39"></a>      <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,</span>
<span id="cb392-40"><a href="gen.html#cb392-40"></a>      <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>)</span>
<span id="cb392-41"><a href="gen.html#cb392-41"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;0.01&quot;</span>, <span class="st">&quot;0.1&quot;</span>, <span class="st">&quot;0.25&quot;</span>, <span class="st">&quot;0.5&quot;</span>),</span>
<span id="cb392-42"><a href="gen.html#cb392-42"></a>       <span class="dt">title =</span> <span class="st">&quot;All. Freq.&quot;</span>, </span>
<span id="cb392-43"><a href="gen.html#cb392-43"></a>       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;green&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;black&quot;</span>),</span>
<span id="cb392-44"><a href="gen.html#cb392-44"></a>       <span class="dt">lty =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/drift_06-1.png" width="672" /></p>
<p>Facciamo un ulteriore passaggio e cerchiamo di capire on un approccio diverso quanto influente è il numero di individui per il mantenimento delle frequenze alleliche. Ritorniamo un secondo allo scenario alla Robinson Crusoe di cui abbiamo parlato all’inizio del capitolo: è molto probabile che il numero dei nuovi individui che fonderanno una nuova popolazione (le zatterine che arrivano sull’isola sperduta) sarà diverso (probabilmente più piccolo) di quello di origine. Che effetto ha questa variazione sulla frequenza allelica nella popolazione che si formerà nell’isola?</p>
<p>Intuitivamente, quando la dimensione del campione (<span class="math inline">\(N_{s}\)</span>) si avvicina a quella della popolazione reale (<span class="math inline">\(N_{p}\)</span>) possiamo essere ragionevolmente sicuri che i paramteri che andiamo a stimare (nello specifico, le frequenze alleliche) si avvicineranno molto al valore reale. Viceversa, se N<span class="math inline">\(_{s}\)</span> &lt;&lt; N<span class="math inline">\(_{p}\)</span> la varianza associata con la stima dei nostri parametri sarà molto larga e quindi la nostra stima non accurata. In altre parole, più grande è il numero di naufraghi che arrivano sull’isola deserta, più probabile che questi naufraghi riescano a catturare tutta la variabilità genetica presente nella popolazione di origine. Viceversa, più piccolo il numero di naufraghi, più grande sarà la probabilità che ci sia una differenza tra le frequenze geniche della popolazione sorgente e quella appena formata.</p>
<p>Un grafico ci aiuterà a capire meglio. Partiamo con una popolazione formata da individui con un singolo gene bi-allelico. Non ci interessa tanto sapere quanto è grande la nostra popolazione, ma partiamo con l’assunto che le frequenze alleliche iniziali siano <span class="math inline">\(p_{A}\)</span> = <span class="math inline">\(p_{a}\)</span> = 0.5. Andremo a simulare ciò che succede alle frequenze alleliche campionando da questa popolazione un numero variabile di individui.</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="gen.html#cb393-1"></a><span class="co"># pacchetti necessari per svolgere la simulazione</span></span>
<span id="cb393-2"><a href="gen.html#cb393-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb393-3"><a href="gen.html#cb393-3"></a><span class="kw">library</span>(RColorBrewer)</span>
<span id="cb393-4"><a href="gen.html#cb393-4"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb393-5"><a href="gen.html#cb393-5"></a><span class="kw">library</span>(phangorn)</span>
<span id="cb393-6"><a href="gen.html#cb393-6"></a></span>
<span id="cb393-7"><a href="gen.html#cb393-7"></a><span class="co"># un gene, due alleli</span></span>
<span id="cb393-8"><a href="gen.html#cb393-8"></a>alleles &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;a&quot;</span>)</span>
<span id="cb393-9"><a href="gen.html#cb393-9"></a></span>
<span id="cb393-10"><a href="gen.html#cb393-10"></a><span class="co"># il numero di indiviui che andremo a campionare</span></span>
<span id="cb393-11"><a href="gen.html#cb393-11"></a>n_sizes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">500</span>,<span class="dv">1000</span>)</span>
<span id="cb393-12"><a href="gen.html#cb393-12"></a></span>
<span id="cb393-13"><a href="gen.html#cb393-13"></a><span class="co"># campioniamo 50 volte ognuno dei valori di n_sizes</span></span>
<span id="cb393-14"><a href="gen.html#cb393-14"></a>df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">N =</span> <span class="kw">rep</span>(n_sizes, <span class="dt">each=</span><span class="dv">50</span>),</span>
<span id="cb393-15"><a href="gen.html#cb393-15"></a>                 <span class="dt">Freq_A =</span> <span class="ot">NA</span>,</span>
<span id="cb393-16"><a href="gen.html#cb393-16"></a>                 <span class="dt">Freq_a =</span> <span class="ot">NA</span>)</span>
<span id="cb393-17"><a href="gen.html#cb393-17"></a></span>
<span id="cb393-18"><a href="gen.html#cb393-18"></a><span class="co"># loop per popolare il dataframe</span></span>
<span id="cb393-19"><a href="gen.html#cb393-19"></a><span class="cf">for</span>(row <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(df)) {</span>
<span id="cb393-20"><a href="gen.html#cb393-20"></a>  <span class="co"># selezione casuale di alleli </span></span>
<span id="cb393-21"><a href="gen.html#cb393-21"></a>  a &lt;-<span class="st"> </span><span class="kw">sample</span>(alleles, <span class="dt">size =</span> df<span class="op">$</span>N[row], <span class="dt">replace =</span> T)</span>
<span id="cb393-22"><a href="gen.html#cb393-22"></a>  <span class="co"># calcolare la frequenza di uno degli alleli</span></span>
<span id="cb393-23"><a href="gen.html#cb393-23"></a>  f &lt;-<span class="st"> </span><span class="kw">sum</span>( a <span class="op">==</span><span class="st"> &quot;A&quot;</span> ) <span class="op">/</span><span class="st"> </span><span class="kw">length</span>(a)</span>
<span id="cb393-24"><a href="gen.html#cb393-24"></a>  <span class="co"># assegna il valore nel dataframe</span></span>
<span id="cb393-25"><a href="gen.html#cb393-25"></a>  df<span class="op">$</span>Freq_A[row] &lt;-<span class="st"> </span>f</span>
<span id="cb393-26"><a href="gen.html#cb393-26"></a>  df<span class="op">$</span>Freq_a[row] &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span>f</span>
<span id="cb393-27"><a href="gen.html#cb393-27"></a>}</span>
<span id="cb393-28"><a href="gen.html#cb393-28"></a></span>
<span id="cb393-29"><a href="gen.html#cb393-29"></a><span class="co"># calcolare valori medi di frequenza di A e a</span></span>
<span id="cb393-30"><a href="gen.html#cb393-30"></a><span class="co"># per ognuno dei valori di n_sizes</span></span>
<span id="cb393-31"><a href="gen.html#cb393-31"></a>df_mean_freq_N &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb393-32"><a href="gen.html#cb393-32"></a><span class="st">  </span><span class="kw">group_by</span>(<span class="kw">as.factor</span>(N)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb393-33"><a href="gen.html#cb393-33"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">A =</span> <span class="kw">mean</span>(Freq_A),</span>
<span id="cb393-34"><a href="gen.html#cb393-34"></a>            <span class="dt">a =</span> <span class="kw">mean</span>(Freq_a))</span>
<span id="cb393-35"><a href="gen.html#cb393-35"></a></span>
<span id="cb393-36"><a href="gen.html#cb393-36"></a><span class="co"># calcolare valori di deviazione standard </span></span>
<span id="cb393-37"><a href="gen.html#cb393-37"></a><span class="co"># di frequenza di A e a</span></span>
<span id="cb393-38"><a href="gen.html#cb393-38"></a><span class="co"># per ognuno dei valori di n_sizes</span></span>
<span id="cb393-39"><a href="gen.html#cb393-39"></a>df_sd_freq_N &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb393-40"><a href="gen.html#cb393-40"></a><span class="st">  </span><span class="kw">group_by</span>(<span class="kw">as.factor</span>(N)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb393-41"><a href="gen.html#cb393-41"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">A =</span> <span class="kw">sd</span>(Freq_A),</span>
<span id="cb393-42"><a href="gen.html#cb393-42"></a>            <span class="dt">a =</span> <span class="kw">sd</span>(Freq_a))</span>
<span id="cb393-43"><a href="gen.html#cb393-43"></a></span>
<span id="cb393-44"><a href="gen.html#cb393-44"></a><span class="co"># organizzare i valori medi in una matrice</span></span>
<span id="cb393-45"><a href="gen.html#cb393-45"></a>df_mean_freq_N_mtrx &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(df_mean_freq_N[,<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>])</span>
<span id="cb393-46"><a href="gen.html#cb393-46"></a><span class="kw">rownames</span>(df_mean_freq_N_mtrx) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">500</span>,<span class="dv">1000</span>)</span>
<span id="cb393-47"><a href="gen.html#cb393-47"></a><span class="co"># organizzare i valori di sd in una matrice</span></span>
<span id="cb393-48"><a href="gen.html#cb393-48"></a>df_sd_freq_N_mtrx &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(df_sd_freq_N[,<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>])</span>
<span id="cb393-49"><a href="gen.html#cb393-49"></a><span class="kw">rownames</span>(df_sd_freq_N_mtrx) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">500</span>,<span class="dv">1000</span>)</span>
<span id="cb393-50"><a href="gen.html#cb393-50"></a><span class="co"># funzione per aggiungere barre di sd ad un </span></span>
<span id="cb393-51"><a href="gen.html#cb393-51"></a><span class="co"># grafico a barre</span></span>
<span id="cb393-52"><a href="gen.html#cb393-52"></a>sd.bar &lt;-<span class="st"> </span><span class="cf">function</span>(x, y,</span>
<span id="cb393-53"><a href="gen.html#cb393-53"></a>                      upper, <span class="dt">lower =</span> upper, <span class="dt">length =</span> <span class="fl">0.1</span>, ...){</span>
<span id="cb393-54"><a href="gen.html#cb393-54"></a>  <span class="kw">arrows</span>(x, y<span class="op">+</span>upper, x, y<span class="op">-</span>lower, <span class="dt">angle =</span> <span class="dv">90</span>,</span>
<span id="cb393-55"><a href="gen.html#cb393-55"></a>         <span class="dt">code =</span> <span class="dv">3</span>, <span class="dt">length =</span> length, ...)</span>
<span id="cb393-56"><a href="gen.html#cb393-56"></a>}</span>
<span id="cb393-57"><a href="gen.html#cb393-57"></a></span>
<span id="cb393-58"><a href="gen.html#cb393-58"></a><span class="co"># creare grafico</span></span>
<span id="cb393-59"><a href="gen.html#cb393-59"></a>df_mean_freq_N_mtrx.blt &lt;-<span class="kw">barplot</span>(df_mean_freq_N_mtrx, <span class="dt">beside =</span> T, </span>
<span id="cb393-60"><a href="gen.html#cb393-60"></a>        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dt">col =</span> <span class="kw">rev</span>(<span class="kw">brewer.pal</span>(<span class="dv">7</span>, <span class="st">&quot;Blues&quot;</span>)),</span>
<span id="cb393-61"><a href="gen.html#cb393-61"></a>        <span class="dt">xlab =</span> <span class="st">&quot;Alleli&quot;</span>,</span>
<span id="cb393-62"><a href="gen.html#cb393-62"></a>        <span class="dt">ylab =</span> <span class="st">&quot;Frequenza&quot;</span>)</span>
<span id="cb393-63"><a href="gen.html#cb393-63"></a><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">500</span>,<span class="dv">1000</span>),</span>
<span id="cb393-64"><a href="gen.html#cb393-64"></a>       <span class="dt">fill =</span> <span class="kw">rev</span>(<span class="kw">brewer.pal</span>(<span class="dv">7</span>, <span class="st">&quot;Blues&quot;</span>)), <span class="dt">title =</span> <span class="st">&quot;N&quot;</span>, <span class="dt">horiz =</span> T)</span>
<span id="cb393-65"><a href="gen.html#cb393-65"></a><span class="kw">lines</span>(<span class="dt">x =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">16</span>, <span class="dv">1</span>), <span class="dt">y =</span> <span class="kw">rep</span>(<span class="fl">0.5</span>, <span class="dv">17</span>),</span>
<span id="cb393-66"><a href="gen.html#cb393-66"></a>      <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb393-67"><a href="gen.html#cb393-67"></a><span class="kw">sd.bar</span>(df_mean_freq_N_mtrx.blt, df_mean_freq_N_mtrx, df_sd_freq_N_mtrx)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/drift_07-1.png" width="672" /></p>
<p>È facile vedere come i valori medi delle frequenze alleliche nei nostri campioni simulati sono abbastanza costanti (notare la riga rossa che taglia il grafico ad una frequenza di 0.5). Quello che varia significativamente da un valore di N all’altro è la deviazione standard associata alle nostre frequenze. Volendo semplificare il concetto ancora di più, più piccolo è il valore del campione <span class="math inline">\(N_{s}\)</span> più alta è la probabilità di vedere cambiata la frequenza allelica nelle generazioni successive. Da un punto di vista evolutivo questo è molto importante. Quando una popolazione subisce una drastica riduzione della popolazione (un collo di bottiglia) la sua composizione allelica sarà, molto probabilmente, diversa da quella precedente.</p>
<p>In effetti, è possibile calcolare la probabilità di una certa frequenza allelica nella generazione successiva. I nostri assunti sono accoppiamento casuale ed un <span class="math inline">\(N\)</span> piccolo. Lavorando con un gene biallelico questo calcolo si può effettuare utilizzando un’espansione binomiale.</p>
<p><span class="math display">\[\frac{2N!}{N_{A}!(2N-N_{A})!} p_A^{N_A} (1-p_A)^{2N-N_A}\]</span></p>
<p>La prima parte dell’espansione (<span class="math inline">\(\frac{2N!}{N_{A}!(2N-N_{A})!} p_A^{N_A}\)</span>) calcola il numero di combinazioni che abbiamo per ottenere esattamente <span class="math inline">\(N_A\)</span> volte l’allele <span class="math inline">\(A\)</span> pescando a caso dalla nostra popolazione <span class="math inline">\(2N\)</span>. La seconda parte dell’espansione (<span class="math inline">\(p_A^{N_A} (1-p_A)^{2N-N_A}\)</span>) calcola la probabilità di ognuna di queste combinazioni a partire dalla frequenza <span class="math inline">\(p_A\)</span> dell’allele <span class="math inline">\(A\)</span>.</p>
<p>Svolgiamo un piccolo esempio per chiarirci le idee. Immaginiamo di avere una popolazione di 20 individui (<span class="math inline">\(N = 20\)</span>) tutti eterozigoti per il gene <span class="math inline">\(A\)</span> (per <span class="math inline">\(T_0\)</span>, <span class="math inline">\(p_A\)</span> = <span class="math inline">\(p_a\)</span> = 0.5, e quindi <span class="math inline">\(N_A\)</span> = <span class="math inline">\(N_a\)</span> = 20). Calcoliamo la probabilità di ottenere esattamente 20 copie dell’allele <span class="math inline">\(A\)</span> nella generazione successiva (ovvero <span class="math inline">\(N_A\)</span> = 20 a <span class="math inline">\(T_1\)</span>). Sostituiamo i valori nella nostra espansione e poi andiamo a risolverla.</p>
<p><span class="math display">\[\frac{2*20!}{20!((2*20)-20)!} 0.5^{20} (1-0.5)^{(2*20)-20}\]</span></p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="gen.html#cb394-1"></a>p &lt;-<span class="st"> </span><span class="fl">0.5</span></span>
<span id="cb394-2"><a href="gen.html#cb394-2"></a>N &lt;-<span class="st"> </span><span class="dv">20</span></span>
<span id="cb394-3"><a href="gen.html#cb394-3"></a>N.A &lt;-<span class="st"> </span><span class="dv">20</span></span>
<span id="cb394-4"><a href="gen.html#cb394-4"></a></span>
<span id="cb394-5"><a href="gen.html#cb394-5"></a>(coef &lt;-<span class="st"> </span><span class="kw">factorial</span>(<span class="dv">2</span><span class="op">*</span>N)<span class="op">/</span><span class="st"> </span>(<span class="kw">factorial</span>(N.A)<span class="op">*</span><span class="kw">factorial</span>(<span class="dv">2</span><span class="op">*</span>N <span class="op">-</span><span class="st"> </span>N.A)))</span></code></pre></div>
<pre><code>## [1] 137846528820</code></pre>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="gen.html#cb396-1"></a>(prob &lt;-<span class="st"> </span>p<span class="op">^</span>N.A <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>p)<span class="op">^</span>(<span class="dv">2</span><span class="op">*</span>N<span class="op">-</span>N.A))</span></code></pre></div>
<pre><code>## [1] 0.0000000000009094947</code></pre>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="gen.html#cb398-1"></a>(Prob.<span class="fl">20.</span>A &lt;-<span class="st"> </span>coef<span class="op">*</span>prob)</span></code></pre></div>
<pre><code>## [1] 0.1253707</code></pre>
<p>Questo numero ci dice che la probabilità che la frequenza rimanga la stessa da una generazione all’altra (ovvero <span class="math inline">\(N_A\)</span> = 20 a <span class="math inline">\(T_1\)</span>) è solo ~0.125, mentre la probabilità che cambi è di ~0.875. Approfondiamo ancora di più. Costruiamo una distribuzione per vedere con quale probabilità si potrebbero verificare diversi valori di <span class="math inline">\(N_A\)</span>.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="gen.html#cb400-1"></a>N.A &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span>(<span class="dv">2</span><span class="op">*</span>N)</span>
<span id="cb400-2"><a href="gen.html#cb400-2"></a>bino_coef &lt;-<span class="st"> </span><span class="kw">factorial</span>(<span class="dv">2</span><span class="op">*</span>N)<span class="op">/</span>( <span class="kw">factorial</span>(N.A)<span class="op">*</span><span class="kw">factorial</span>(<span class="dv">2</span><span class="op">*</span>N<span class="op">-</span>N.A)) </span>
<span id="cb400-3"><a href="gen.html#cb400-3"></a>bino_prob &lt;-<span class="st"> </span>p<span class="op">^</span>N.A <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span><span class="op">-</span>p)<span class="op">^</span>(<span class="dv">2</span><span class="op">*</span>N<span class="op">-</span>N.A)</span>
<span id="cb400-4"><a href="gen.html#cb400-4"></a>change_prob &lt;-<span class="st"> </span>bino_coef<span class="op">*</span>bino_prob</span>
<span id="cb400-5"><a href="gen.html#cb400-5"></a>df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(N.A, change_prob)</span>
<span id="cb400-6"><a href="gen.html#cb400-6"></a><span class="kw">barplot</span>(df<span class="op">$</span>change_prob,</span>
<span id="cb400-7"><a href="gen.html#cb400-7"></a>        <span class="dt">names.arg =</span> df<span class="op">$</span>N.A,</span>
<span id="cb400-8"><a href="gen.html#cb400-8"></a>        <span class="dt">cex.names =</span> <span class="fl">0.7</span>,</span>
<span id="cb400-9"><a href="gen.html#cb400-9"></a>        <span class="dt">xlab =</span> <span class="kw">expression</span>(<span class="kw">italic</span>(N)[A]),</span>
<span id="cb400-10"><a href="gen.html#cb400-10"></a>        <span class="dt">ylab =</span> <span class="st">&quot;Prob.&quot;</span>,</span>
<span id="cb400-11"><a href="gen.html#cb400-11"></a>        <span class="dt">las =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/drift_09-1.png" width="672" /></p>
<p>La distribuzione ci racconta una storia interessante, ovvero che esiste una probabilità (anche se estremamente piccola!) che in una sola generazione un allele venga perso (e l’altro vada a fissazione). Ovviamente questa probabilità è talmente piccola da poter essere scartata, in particolare se si sta lavorando su scale temporali relativamente brevi.</p>
<p>Adesso cambiamo marcia e andiamo a vedere come poter quantificare le differenze che si creano tra diverse popolazioni che, per qualche motivo, sono separate o strutturate da un punto di vista genetico.</p>
</div>
<div id="gen_str" class="section level2">
<h2><span class="header-section-number">5.3</span> Struttura genetica delle popolazioni</h2>
<p>In quasi completo contrasto con la casualità di cui abbiamo parlato nella precedente sezione di questo capitolo, qui parleremo di Struttura Genetica delle Popolazioni. Gli individui di una popolazione si dicono “strutturati” da un punto di vista genetico quando il loro genotipo non è indipendente dalla loro zona e/o tempo di campionamento. Ad esempio, se non esistesse una struttura genetica di popolazioni ci aspetteremmo di trovare le stesse caratteristiche genetiche in individui di una certa specie che sono campionati in aree o tempi distinti. Per una specie di pianta che è distribuita sui declivi di una collina ci possiamo aspettare, in assenza di struttura genetica di popolazione, la stessa composizione allelica per individui campionati ai piedi e sulla cima della collina. L’interazione delle forze evolutive, della deriva genetica, e dell’ambiente, in realtà, contribuiscono a creare una struttura genetica che puo essere più o meno accentuata a seconda del tipo e dell’intensità delle forze in gioco.</p>
<p><img src="Images/02-03.png" /></p>
<div id="le-statistiche-f" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Le statistiche F</h3>
<p>In uno dei più importanti lavori della genetica di popolazioni pubblicati all’inizio del secolo scorso, Sewal Wright descrisse la predicibile relazione tra il grado di differenziazione genetica tra popolazioni e l’influenza di imporatanti processi evolutivi quali la migrazione, la mutazione e la deriva genetica <span class="citation">(Wright <a href="#ref-Wright1931" role="doc-biblioref">1931</a>, <a href="#ref-Wright1951" role="doc-biblioref">1951</a>; Holsinger and Weir <a href="#ref-Holsinger2009" role="doc-biblioref">2009</a>)</span>.</p>
<p>Le statistiche F introdotte da Wright <span class="citation">(Wright <a href="#ref-Wright1931" role="doc-biblioref">1931</a>, <a href="#ref-Wright1951" role="doc-biblioref">1951</a>)</span> sono uno degli strumenti maggiormente usati per descrivere la struttura genetica di popolazione. Tre principali indici di differenziamento vengono usati:</p>
<ul>
<li><p><span class="math inline">\(F_{IS}\)</span>: la correlazione tra i gameti di un individuo rispetto alla sua sottopopolazione;</p></li>
<li><p><span class="math inline">\(F_{IT}\)</span>: la correlazione tra i gameti di un individuo rispetto all’intera popolazione;</p></li>
<li><p><span class="math inline">\(F_{ST}\)</span>: la correlazione tra gameti presi in maniera casuale all’interno di una popolazione rispetto all’intera popolazione.</p></li>
</ul>
<p>Ognuno di questi indici è stato, nel corso degli anni, interpretato e “chiamato” con nomi diversi. Ad esempio Cockerham dimostra che i parametri <span class="math inline">\(f\)</span>, <span class="math inline">\(θ\)</span> e <span class="math inline">\(F\)</span> hanno le caratteristiche approssimabili rispettivamente a <span class="math inline">\(F_{IS}\)</span>, <span class="math inline">\(F_{ST}\)</span> ed <span class="math inline">\(F_{IS}\)</span> <span class="citation">(Cockerham <a href="#ref-Cockerham1969" role="doc-biblioref">1969</a>)</span>.</p>
<p>La trattazione di questi indici è ampliamente documentata nelle fonti citate. Nelle seguenti sezioni andremo a vedere come è possibile stimare e visualizzare la struttura genetica di popolazione usando un metodo differente.</p>
</div>
<div id="inferenza-bayesiana-con-structure" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Inferenza Bayesiana con STRUCTURE</h3>
<p>Uno degli approcci che vengono usati sistematicamente per l’analisi della struttura genetica di popolazioni è quello dell’individuazione di clusters di campioni che sono maggiormente simili tra loro, da un punto di vista genetico, rispetto ad altri. Rivoluzionario, da questo punto di vista, fù il contributo del software <a href="http://web.stanford.edu/group/pritchardlab/structure.html">STRUCTURE</a> che utilizza un modello Bayesiano e il calcolo di una <em>posterior probability</em> per l’inferenza di gruppi di campioni piu o meno simili tra loro <span class="citation">(Pritchard, Stephens, and Donnelly <a href="#ref-Pritchard2000" role="doc-biblioref">2000</a>)</span>.</p>
<p><strong>STRUCTURE</strong> è un software scritto usando il linguaggio Java ed è quindi possibile scaricarlo ed utilizzarlo in maniera indipendente da <span class="math inline">\(R\)</span>. Tramite l’interfaccia <span class="math inline">\(R\)</span> e l’utilizzo di pacchetti specifici è però possibile parallelizzare il lavoro svolto dal software, in modo da poter drammaticamente velocizzare il calcolo delle probabilità a posteriori.</p>
<p>Prima di procedere con un esempio pratico su come è possibile usare <span class="math inline">\(R\)</span> per velocizzare le nostre analisi è doveroso fare una precisazione di tipo tecnico. Il modo in cui i computers usano i loro “cores” per il calcolo parallelo non è standardizzato e varia a seconda del sistema operativo (OS) che viene utilizzato!! È quindi possibile che il lettore incontrerà una serie di difficoltà tecniche quando proverà a replicare il codice riportato. Un’utile fonte di informazioni per capire come organizzare al meglio il lavoro a seconda del proprio OS si può trovare in questo <a href="https://www.molecularecologist.com/2013/09/03/using-r-to-run-parallel-analyses-of-population-genetic-data-in-structure-parallelstructure/">blog-post</a>. Ci sono poi numerose altre risorse sulla rete. Gli esempi qui riportati sono stati eseguiti utilizzando un iMac del 2017 (4.2 GHz Quad-Core Intel Core i7) con macOS Catalina 10.15.7.</p>
<p>Lavoreremo con un dataset composto da 182 individui che sono stati tipizzati ad 11 microsatelliti <span class="citation">(Taylor and Hoffman <a href="#ref-Taylor2012" role="doc-biblioref">2012</a>)</span>. Il dataset può essere scaricato <a href="https://www.dropbox.com/preview/manuscripts/books/monografia_R/Libro_MIR/data/06_genetics/Taylor_et_al_2012/genotype_input.txt?role=personal">qui</a>. Sarà anche necessario un file con le istruzioni necessarie al programma <strong>STRUCTURE</strong> che può essere scaricato <a href="https://www.dropbox.com/preview/manuscripts/books/monografia_R/Libro_MIR/data/06_genetics/Taylor_et_al_2012/joblist.txt?role=personal">qui</a>.</p>
<p><strong>STRUCTURE</strong> dovrà essere installato sul nostro computer, perché la routine riportata qui non si sostituisce all’algoritmo di calcolo bayesiano implementata nel programma. Piuttosto, usiamo <span class="math inline">\(R\)</span> per fare in modo che l’agoritmo di <strong>STRUCTURE</strong> venga distribuito su un certo numero di cores (a seconda della disponibilità sul nostro computer) e riduca drammaticamente il tempo di calcolo della probabilità.</p>
<p>Sarà anche necessario installare e richiamare due pacchetti specifici: <a href="https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf"><em>parallel</em></a> e <a href="https://rdrr.io/rforge/ParallelStructure/"><em>ParallelStructure</em></a>.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="gen.html#cb401-1"></a><span class="co"># per sfruttare le possibilità di calcolo in parallelo</span></span>
<span id="cb401-2"><a href="gen.html#cb401-2"></a><span class="kw">library</span>(parallel) </span>
<span id="cb401-3"><a href="gen.html#cb401-3"></a><span class="co"># per interagire con STRUCTURE e specificare i paramteri per l&#39;analisi</span></span>
<span id="cb401-4"><a href="gen.html#cb401-4"></a><span class="kw">library</span>(ParallelStructure) </span></code></pre></div>
<p>Una volta installati e richiamati i pacchetti dovrebbe essere possibile far correre l’analisi. prima però andiamo a vedere i file di input e le istruzioni da impartire a <strong>STRUCTURE</strong>.</p>
<div class="figure">
<img src="Images/02-04.png" alt="" />
<p class="caption">File di input contenente il genotipo degli individui da analizzare con <strong>STRUCTURE</strong>.</p>
</div>
<p>In questo file di testo tabulato sono contenuti i genotipi degli individui da analizzare. Si tratta di 182 campioni raccolti da 16 diversi siti e tipizzati per 11 loci microsatelliti. Ogni riga contiene un individuo. La prima colonna contiene un ID specifico del campione, la seconda un indice numerico relativo al sito di campionamento e a seguire ci sono 22 colonne colonne ognuna contenente l’allele relativo al locus analizzato. È convenzione indicare con il valore -9 quei loci per i quali non è disponibile il dato.</p>
<div class="figure">
<img src="Images/02-05.png" alt="" />
<p class="caption">File di istruzioni da impartire a <strong>STRUCTURE</strong>.</p>
</div>
<p>In questo secondo file tabulato sono contenute le istruzioni specifiche da impartire a <strong>STRUCTURE</strong> per indicargli per quanto tempo far correre l’analisi. La prima colonna contiene un ID specifico del singolo set di istruzioni. La seconda colonna contiene un’istruzione relativa a quale sito di campionamento da usare nell’analisi. Nel nostro esempio useremo sempre tutti i campioni e tutti i siti di campionamento. La terza colonna contiene un numero relativo ai valori di <em>K</em> da testare. In altre parole, con le prime tre righe stiamo chiedendo a <strong>STRUCTURE</strong> di calcolare la probabilità a posteriori che tutti i nostri campioni vengano da un singolo cluster genetico. È buona norma ripetere il calcolo, per ogni valore di <em>K</em>, almeno 15-20 volte. Nel nostro esempio abbiamo effettuato il calcolo solo 3 volte per ogni valore di <em>K</em>. Le ultime due colonne sono relative al <em>burn-in</em> e al numero di <em>MCMC</em> che il programma effettuerà per calcolare la probabilità.</p>
<p>Se tutto è stato preparato e formattato a dovere è possibile far correre l’analisi con il seguente codice. Rimandiamo al manuale di ParallelStructure per una dettagliate desamina di tutti i possibili parametri da inserire e qui ci limitiamo ad evidenziare quelli base.</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="gen.html#cb402-1"></a><span class="co"># Specifica il path per il file binario del programma STRUCTURE</span></span>
<span id="cb402-2"><a href="gen.html#cb402-2"></a>STR_path &lt;-<span class="st"> &#39;YOUR/PATH/TO/STRUCTURE&#39;</span></span>
<span id="cb402-3"><a href="gen.html#cb402-3"></a></span>
<span id="cb402-4"><a href="gen.html#cb402-4"></a><span class="co"># Set di istruzioni per l&#39;inizio dell&#39;analisi</span></span>
<span id="cb402-5"><a href="gen.html#cb402-5"></a><span class="kw">parallel_structure</span>(<span class="dt">structure_path =</span> STR_path, <span class="co"># path per STRUCTURE</span></span>
<span id="cb402-6"><a href="gen.html#cb402-6"></a>                   <span class="dt">joblist =</span> <span class="st">&#39;joblist.txt&#39;</span>,   <span class="co"># specifica il file con le informazioni per STRUCTURE</span></span>
<span id="cb402-7"><a href="gen.html#cb402-7"></a>                   <span class="dt">n_cpu =</span> <span class="dv">6</span>,                 <span class="co"># specifica il numero di cores da usare</span></span>
<span id="cb402-8"><a href="gen.html#cb402-8"></a>                   <span class="dt">infile =</span> <span class="st">&#39;input.txt&#39;</span>,      <span class="co"># input file con il genotipo dei campioni</span></span>
<span id="cb402-9"><a href="gen.html#cb402-9"></a>                   <span class="dt">outpath =</span> <span class="st">&#39;Results/&#39;</span>,      <span class="co"># cartella dove trovare i risultati</span></span>
<span id="cb402-10"><a href="gen.html#cb402-10"></a>                   <span class="dt">label =</span> <span class="dv">1</span>,                 <span class="co"># </span></span>
<span id="cb402-11"><a href="gen.html#cb402-11"></a>                   <span class="dt">popdata =</span> <span class="dv">1</span>,               <span class="co">#</span></span>
<span id="cb402-12"><a href="gen.html#cb402-12"></a>                   <span class="dt">numinds =</span> <span class="dv">182</span>,             <span class="co"># numero di individui </span></span>
<span id="cb402-13"><a href="gen.html#cb402-13"></a>                   <span class="dt">numloci =</span> <span class="dv">11</span>,              <span class="co"># numero di loci</span></span>
<span id="cb402-14"><a href="gen.html#cb402-14"></a>                   <span class="dt">printqhat =</span> <span class="dv">0</span>,             <span class="co">#</span></span>
<span id="cb402-15"><a href="gen.html#cb402-15"></a>                   <span class="dt">onerowperind =</span> <span class="dv">1</span>,          <span class="co">#</span></span>
<span id="cb402-16"><a href="gen.html#cb402-16"></a>                   <span class="dt">missing =</span> <span class="dv">-9</span>)              <span class="co"># carattere usato per i dati mancanti</span></span></code></pre></div>
<p>Con il dataset usato ed i paramteri specificati nello script l’analisi dovrebbe durare circa 2.5 ore. I risultati sono contenuti nella cartella che abbiamo chiamato Results. Questi file non ci danno ancora una risposta precisa alla domanda “Qual’è il numero minimo di clusters genetici in cui i nostri campioni possono essere classificati?”. Uno dei modi per arrivare a questa conclusione è l’utilizzo del parametro <span class="math inline">\(∆K\)</span> derivata dal secondo-ordine di variazione nel Ln <span class="math inline">\(P\)</span>(D) come descritto in <span class="citation">(Evanno, Regnaut, and Goudet <a href="#ref-Evanno2005" role="doc-biblioref">2005</a>)</span>. Il calcolo di <span class="math inline">\(∆K\)</span> può essere fatto tramite <a href="http://taylor0.biology.ucla.edu/structureHarvester/">Structure Harvester</a>, ma sarà prima necessario formattare i dati nel modo giusto. Se stiamo lavorando su un sistema UNIX dovrebbe essere possibile preparare il file usando il seguente codice:</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="gen.html#cb403-1"></a><span class="co"># spostimoci nella cartella dei risultati</span></span>
<span id="cb403-2"><a href="gen.html#cb403-2"></a><span class="kw">setwd</span>(<span class="st">&quot;~/Desktop/Results/&quot;</span>)</span>
<span id="cb403-3"><a href="gen.html#cb403-3"></a></span>
<span id="cb403-4"><a href="gen.html#cb403-4"></a><span class="co"># richiamiamo dei comandi di sistema per creare un file compresso .zip da usare</span></span>
<span id="cb403-5"><a href="gen.html#cb403-5"></a><span class="co"># sulla pagina web di Structure Harvester</span></span>
<span id="cb403-6"><a href="gen.html#cb403-6"></a><span class="kw">system</span>(<span class="st">&quot;mkdir ForHarvester&quot;</span>)</span>
<span id="cb403-7"><a href="gen.html#cb403-7"></a><span class="kw">system</span>(<span class="st">&quot;mv *_f ForHarvester&quot;</span>)</span>
<span id="cb403-8"><a href="gen.html#cb403-8"></a><span class="kw">system</span>(<span class="st">&quot;zip -r ForHarvester.zip ForHarvester&quot;</span>)</span></code></pre></div>
<p>Il server online produce un risultato in un paio di minuti (a seconda del carico di lavoro che ha). Il valore di <span class="math inline">\(∆K\)</span> ottenuto corrisponde al numero di cluster genetici identificati nei nostri campioni. Secondo questi valori <span class="math inline">\(K\)</span> = 3 meglio approssima il numero di clusters gentici differenti nei nostri capmioni.</p>
<p><img src="Images/02-06.png" alt="Valori di ∆K come calcolati da Structure Harvester" />
Possiamo andare, ora, a controllare quelli che sono i valori delle probabilità relative di ogni individuo di appartenere ad uno dei 3 cluster genetici. Il modo più semplice per farlo è, come spesso succede, quello di creare un bel grafico. I dati di partenza sono disponibili <a href="https://www.dropbox.com/preview/manuscripts/books/monografia_R/Libro_MIR/data/06_genetics/Taylor_et_al_2012/k3_barplot_data.txt?role=personal">qui</a> e il codice per creare il grafico è qui sotto. Il comando <em>read.table()</em> permette il recupero di dati anche da connesioni remote, senza la necessità di scaricare il file sul nostro computer.</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="gen.html#cb404-1"></a>str.K3 &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://www.dropbox.com/s/g7bj8gccc5dotp8/k3_barplot_data.txt?raw=1&quot;</span>,</span>
<span id="cb404-2"><a href="gen.html#cb404-2"></a>                     <span class="dt">header =</span> T)</span>
<span id="cb404-3"><a href="gen.html#cb404-3"></a></span>
<span id="cb404-4"><a href="gen.html#cb404-4"></a>str.K3.mtx &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(str.K3[, <span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)])</span>
<span id="cb404-5"><a href="gen.html#cb404-5"></a><span class="kw">rownames</span>(str.K3.mtx) &lt;-<span class="st"> </span>str.K3[, <span class="dv">1</span>]</span>
<span id="cb404-6"><a href="gen.html#cb404-6"></a></span>
<span id="cb404-7"><a href="gen.html#cb404-7"></a><span class="kw">barplot</span>(<span class="kw">t</span>(str.K3.mtx),</span>
<span id="cb404-8"><a href="gen.html#cb404-8"></a>        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;green&quot;</span>, <span class="st">&quot;blue&quot;</span>),</span>
<span id="cb404-9"><a href="gen.html#cb404-9"></a>        <span class="dt">xlab =</span> <span class="st">&quot;Individuals&quot;</span>,</span>
<span id="cb404-10"><a href="gen.html#cb404-10"></a>        <span class="dt">ylab =</span> <span class="st">&quot;Post. Probability&quot;</span>,</span>
<span id="cb404-11"><a href="gen.html#cb404-11"></a>        <span class="dt">las =</span> <span class="dv">2</span>,</span>
<span id="cb404-12"><a href="gen.html#cb404-12"></a>        <span class="dt">cex.names =</span> <span class="fl">.3</span>)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/str4-1.png" width="672" /></p>
<p>Sull’asse delle X abbiamo gli individui, mentre sull’asse delle y abbiamo il valore di probabilità che, basandosi sul genotipo, ogni individuo appartengo ad uno 3 tre clusters genetici che il programma ha evidenziato (caratterizzati dai tre colori differenti). Questo risultato ci dice che anche se i nostri campioni provengono da 16 siti di campionamento differenti, siamo in grado di riconoscere solo 3 unità genetiche distinte una dall’altra, evidenziando il fatto che tra molti dei siti di campionamento avviene, probabilmente, un elevato flusso genico.</p>
</div>
</div>
<div id="gen_phylo" class="section level2">
<h2><span class="header-section-number">5.4</span> Filogenesi</h2>
<p>Le ricostruzioni filogenetiche sono forse uno degli aspetti più affascinanti della biologia evolutiva, poiché ci permettono di indagare quelli che sono i rapporti di discendenza tra le diverse specie, e ci danno uno spaccato della storia evolutiva delle diverse forme biologiche esistenti ed estinte.</p>
<p><img src="Images/02-07.png" /></p>
<p>Fino ad ora la maggior parte delle cose che abbiamo visto in questo capitolo sulla genetica ed <span class="math inline">\(R\)</span> sono state abbastanza intuitive, sopratutto perché i dati che abbiamo usato sono di tipo numerico. Le cose cambiano leggermente ora che ci mettiamo a lavorare su un altro tipo di dati che sono relativi alle vere e proprie sequenze di DNA, e quindi stringhe di nucleotidi (i mattoncini che compongono gli acidi nucleici di tutte le forme viventi).</p>
<p>Gli aspetti teorici dietro le ricostruzini filogenetiche presentano un grado di complessita che va ben oltre gli scopi di questo libro. Per questo motivo ci limiteremo a produrre una semplice ricostruzione filogenetica per dimostrare le potenzialità di <span class="math inline">\(R\)</span> anche in questo campo.</p>
<p>Per queste analisi sarà necessario installare e richiamare una serie di pacchetti specifici. Assumendo che i pacchetti siano già presenti sul computer di chi ci legge, li possiamo richiamare tutti quanti con questo comando.</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="gen.html#cb405-1"></a>x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;ade4&quot;</span>, <span class="st">&quot;adegenet&quot;</span>, <span class="st">&quot;ape&quot;</span>, <span class="st">&quot;gridExtra&quot;</span>, <span class="st">&quot;ips&quot;</span>, <span class="st">&quot;pegas&quot;</span>, <span class="st">&quot;phangorn&quot;</span>, <span class="st">&quot;phyloch&quot;</span>, <span class="st">&quot;seqinr&quot;</span>)</span>
<span id="cb405-2"><a href="gen.html#cb405-2"></a><span class="kw">lapply</span>(x, require, <span class="dt">character.only =</span> T)</span>
<span id="cb405-3"><a href="gen.html#cb405-3"></a><span class="kw">rm</span>(x)</span></code></pre></div>
<p>I dati che andremo ad utilizzare provengono da <span class="citation">Morales‐Hojas et al. (<a href="#ref-MoralesHojas2020" role="doc-biblioref">2020</a>)</span> e si riferiscono ad un set di sequenze di DNA di afidi. Il dataset è organizzato in un file <a href="https://en.wikipedia.org/wiki/FASTA">FASTA</a>.</p>
<p><img src="Images/02-08.png" alt="Sequenze provenienti da 196 campioni di afidi collezionati in Inghilterra." />
La prima operazione da fare è quella di caricare il file in <span class="math inline">\(R\)</span>.</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="gen.html#cb406-1"></a>phyDat_dna &lt;-<span class="st"> </span><span class="kw">read.phyDat</span>(<span class="st">&quot;./data/06_genetics/Morales-Hojas_et_al_2020/England_samples_SNPs_polymorphic.fas&quot;</span>,</span>
<span id="cb406-2"><a href="gen.html#cb406-2"></a>                          <span class="dt">format =</span> <span class="st">&quot;fasta&quot;</span>, </span>
<span id="cb406-3"><a href="gen.html#cb406-3"></a>                          <span class="dt">type =</span> <span class="st">&quot;DNA&quot;</span>)</span></code></pre></div>
<p>Per la stima di una filogenesi il primo passaggio è quello di trovare il modello di sostituzione nucleotidica che si adatta maggiormente alle nostre sequenze. Per fare questo possiamo far correre un algoritmo che confronta diversi modelli evolutivi con il nostro dataset e poi identificare quale di qeusti modelli megio descrive le nostre sequenze.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="gen.html#cb407-1"></a>phyDat_dna_modelTest &lt;-<span class="st"> </span><span class="kw">modelTest</span>(phyDat_dna, </span>
<span id="cb407-2"><a href="gen.html#cb407-2"></a>                                  <span class="dt">model =</span> <span class="st">&quot;all&quot;</span>, </span>
<span id="cb407-3"><a href="gen.html#cb407-3"></a>                                  <span class="dt">G =</span> T, <span class="dt">I =</span> T, </span>
<span id="cb407-4"><a href="gen.html#cb407-4"></a>                                  <span class="dt">multicore =</span> T, </span>
<span id="cb407-5"><a href="gen.html#cb407-5"></a>                                  <span class="dt">mc.cores =</span> <span class="dv">4</span>)</span>
<span id="cb407-6"><a href="gen.html#cb407-6"></a></span>
<span id="cb407-7"><a href="gen.html#cb407-7"></a></span>
<span id="cb407-8"><a href="gen.html#cb407-8"></a><span class="kw">plot.default</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(phyDat_dna_modelTest<span class="op">$</span>Model)),</span>
<span id="cb407-9"><a href="gen.html#cb407-9"></a>             <span class="dt">y =</span> phyDat_dna_modelTest<span class="op">$</span>AIC,</span>
<span id="cb407-10"><a href="gen.html#cb407-10"></a>             <span class="dt">type =</span> <span class="st">&#39;p&#39;</span>,</span>
<span id="cb407-11"><a href="gen.html#cb407-11"></a>             <span class="dt">axes =</span> <span class="ot">FALSE</span>,</span>
<span id="cb407-12"><a href="gen.html#cb407-12"></a>             <span class="dt">pch =</span> <span class="dv">21</span>,</span>
<span id="cb407-13"><a href="gen.html#cb407-13"></a>             <span class="dt">bg =</span> <span class="kw">ifelse</span>(phyDat_dna_modelTest<span class="op">$</span>AIC <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(phyDat_dna_modelTest<span class="op">$</span>AIC),</span>
<span id="cb407-14"><a href="gen.html#cb407-14"></a>                         <span class="st">&quot;red&quot;</span>, <span class="st">&quot;black&quot;</span>),</span>
<span id="cb407-15"><a href="gen.html#cb407-15"></a>             <span class="dt">xlab =</span> <span class="st">&quot;Modelli di sostituzione nucleotidica&quot;</span>,</span>
<span id="cb407-16"><a href="gen.html#cb407-16"></a>             <span class="dt">ylab =</span> <span class="st">&quot;AIC&quot;</span>)</span>
<span id="cb407-17"><a href="gen.html#cb407-17"></a><span class="kw">axis</span>(<span class="dt">side =</span> <span class="dv">1</span>, </span>
<span id="cb407-18"><a href="gen.html#cb407-18"></a>     <span class="dt">at =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(phyDat_dna_modelTest<span class="op">$</span>Model)), </span>
<span id="cb407-19"><a href="gen.html#cb407-19"></a>     <span class="dt">labels =</span> <span class="kw">as.character</span>(phyDat_dna_modelTest<span class="op">$</span>Model),</span>
<span id="cb407-20"><a href="gen.html#cb407-20"></a>     <span class="dt">las =</span> <span class="dv">2</span>,</span>
<span id="cb407-21"><a href="gen.html#cb407-21"></a>     <span class="dt">cex.axis =</span> <span class="fl">.4</span>)</span>
<span id="cb407-22"><a href="gen.html#cb407-22"></a><span class="kw">axis</span>(<span class="dt">side =</span> <span class="dv">2</span>,</span>
<span id="cb407-23"><a href="gen.html#cb407-23"></a>     <span class="dt">at =</span> phyDat_dna_modelTest<span class="op">$</span>AIC,</span>
<span id="cb407-24"><a href="gen.html#cb407-24"></a>     <span class="co">#labels = phyDat_dna_modelTest$AIC,</span></span>
<span id="cb407-25"><a href="gen.html#cb407-25"></a>     <span class="dt">las =</span> <span class="dv">2</span>,</span>
<span id="cb407-26"><a href="gen.html#cb407-26"></a>     <span class="dt">cex.axis =</span> <span class="fl">.4</span>)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/phy1_b-1.png" width="672" /></p>
<p>Il modello che meglio approssima le nostre sequenze (usando il parametro AIC) è il TVM+G+I (Transversion model + una certa proporzione di variazione tra siti (con distribuzione <span class="math inline">\(\Gamma\)</span>) + una proporzione di siti invariati).</p>
<p>Il modello migliore per ricostruire questa filogenesi è quindi il TVM+G+I. Purtroppo l’implemetazione di molti di questi modelli evolutivi non è supportata in diversi software per le ricostruzioni filogenetiche. In questi casi, quindi, si cerca di utilizzare il modello più flessibile, i.e. il GTR (General Time Reversible). Come nel precedente capitolo, ricorreremo ad <span class="math inline">\(R\)</span> per eseguire un’analisi utilizzando un sofware terzo, che nel caso specifico si chiama RAxML <span class="citation">(Stamatakis <a href="#ref-Stamatakis2014" role="doc-biblioref">2014</a>)</span>. Il file di input saranno le nostre sequenze allineate che abbiamo precedentemente caricato in formato FASTA.</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="gen.html#cb408-1"></a>MLtree &lt;-<span class="st"> </span>ips<span class="op">::</span><span class="kw">raxml</span>(DNAbin_dna, <span class="co"># DNAbin</span></span>
<span id="cb408-2"><a href="gen.html#cb408-2"></a>                     <span class="dt">m =</span> <span class="st">&quot;GTRGAMMA&quot;</span>, </span>
<span id="cb408-3"><a href="gen.html#cb408-3"></a>                     <span class="dt">f =</span> <span class="st">&quot;a&quot;</span>,</span>
<span id="cb408-4"><a href="gen.html#cb408-4"></a>                     <span class="dt">N =</span> <span class="st">&quot;autoMRE&quot;</span>,</span>
<span id="cb408-5"><a href="gen.html#cb408-5"></a>                     <span class="dt">p =</span> <span class="dv">1234</span>,</span>
<span id="cb408-6"><a href="gen.html#cb408-6"></a>                     <span class="dt">x =</span> <span class="dv">1234</span>, </span>
<span id="cb408-7"><a href="gen.html#cb408-7"></a>                     <span class="dt">exec =</span> <span class="st">&quot;/Applications/RAxML-8.0.3/raxmlHPC-PTHREADS&quot;</span>, </span>
<span id="cb408-8"><a href="gen.html#cb408-8"></a>                     <span class="dt">threads =</span> <span class="dv">4</span>,</span>
<span id="cb408-9"><a href="gen.html#cb408-9"></a>                     <span class="dt">k =</span> T)</span></code></pre></div>
<p>Il calcolo di una filogenesi è, solitamente, un processo lungo, che varia molto a seconda della potenza del computer utilizzato. Nel caso specifico abbiamo salvato l’output che andiamo a caricare per la visualizzazione.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="gen.html#cb409-1"></a>england &lt;-<span class="st"> </span>ape<span class="op">::</span><span class="kw">read.tree</span>(<span class="st">&quot;./data/06_genetics/Morales-Hojas_et_al_2020/England_RAxML_newick.tre&quot;</span>)</span>
<span id="cb409-2"><a href="gen.html#cb409-2"></a></span>
<span id="cb409-3"><a href="gen.html#cb409-3"></a><span class="kw">plot</span>(england)</span></code></pre></div>
<p><img src="02-gen_files/figure-html/phy4-1.png" width="672" /></p>
<p>L’albero è, evidentemente molto complesso. <span class="citation">Paradis (<a href="#ref-Paradis2012" role="doc-biblioref">2012</a>)</span> offre una completa descrizione di come manipolare alberi anche molto complessi come quello appena generato, per poter evidenziare caratteristiche specifiche o particolari aspetti d’interesse.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Cockerham1969">
<p>Cockerham, C. Clark. 1969. “Variance of Gene Frequencies.” <em>Evolution</em> 23 (1): 72. <a href="https://doi.org/10.2307/2406485">https://doi.org/10.2307/2406485</a>.</p>
</div>
<div id="ref-Evanno2005">
<p>Evanno, G., S. Regnaut, and J. Goudet. 2005. “Detecting the number of clusters of individuals using the software STRUCTURE: A simulation study.” <em>Molecular Ecology</em> 14 (8): 2611–20. <a href="https://doi.org/10.1111/j.1365-294X.2005.02553.x">https://doi.org/10.1111/j.1365-294X.2005.02553.x</a>.</p>
</div>
<div id="ref-Holsinger2009">
<p>Holsinger, Kent E, and Bruce S Weir. 2009. “Genetics in geographically structured populations: defining, estimating and interpreting F&lt;sub&gt;st&lt;/sub&gt;.” <em>Nature Reviews. Genetics</em> 10 (9): 639–50. <a href="https://doi.org/10.1038/nrg2611">https://doi.org/10.1038/nrg2611</a>.</p>
</div>
<div id="ref-MoralesHojas2020">
<p>Morales‐Hojas, Ramiro, Jingxuan Sun, Fernando Alvira Iraizoz, Xiaoling Tan, and Julian Chen. 2020. “Contrasting population structure and demographic history of cereal aphids in different environmental and agricultural landscapes.” <em>Ecology and Evolution</em> 10 (18): 9647–62. <a href="https://doi.org/10.1002/ece3.6565">https://doi.org/10.1002/ece3.6565</a>.</p>
</div>
<div id="ref-Paradis2012">
<p>Paradis, Emmanuel. 2012. <em>Analysis of Phylogenetics and Evolution with R</em>. Edited by Giovanni G. Parmigiani Robert Gentleman Kurt Hornik. Second. Use R! Springer, New York, NY.</p>
</div>
<div id="ref-Pritchard2000">
<p>Pritchard, J K, M. Stephens, and P Donnelly. 2000. “Inference of population structure using multilocus genotype data.” <em>Genetics</em> 155 (2): 945–59. <a href="https://doi.org/10.1111/j.1471-8286.2007.01758.x">https://doi.org/10.1111/j.1471-8286.2007.01758.x</a>.</p>
</div>
<div id="ref-Stamatakis2014">
<p>Stamatakis, Alexandros. 2014. “RAxML version 8: A tool for phylogenetic analysis and post-analysis of large phylogenies.” <em>Bioinformatics</em>. <a href="https://doi.org/10.1093/bioinformatics/btu033">https://doi.org/10.1093/bioinformatics/btu033</a>.</p>
</div>
<div id="ref-Taylor2012">
<p>Taylor, Zachary S., and Susan M. G. Hoffman. 2012. “Microsatellite genetic structure and cytonuclear discordance in naturally fragmented populations of deer mice (peromyscus maniculatus).” <em>Journal of Heredity</em> 103 (1): 71–79. <a href="https://doi.org/10.1093/jhered/esr100">https://doi.org/10.1093/jhered/esr100</a>.</p>
</div>
<div id="ref-Wright1951">
<p>Wright, S. 1951. “The genetical structure of populations.” <em>Annals of Eugenics</em> 15: 323–54. <a href="https://doi.org/10.2307/2407273">https://doi.org/10.2307/2407273</a>.</p>
</div>
<div id="ref-Wright1931">
<p>Wright, Sewall. 1931. “Evolution in Mendelian populations.” <em>Bulletin of Mathematical Biology</em> 52 (1-2): 241–95. <a href="https://doi.org/10.1016/S0092-8240(05)80011-4">https://doi.org/10.1016/S0092-8240(05)80011-4</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="base.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="machine-learning-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Libro_MIR.pdf", "Libro_MIR.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
